// <auto-generated />
using System;
using AlxorCore.Logistica.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Logistica.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(LogisticaDbContext))]
    partial class LogisticaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("logistica")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Logistica.Dominio.ConfiguracionLogistica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DigitoExtension")
                        .HasColumnType("integer")
                        .HasColumnName("digito_extension");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("MezclarLotes")
                        .HasColumnType("boolean")
                        .HasColumnName("mezclar_lotes");

                    b.Property<string>("PrefijoGs1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefijo_gs1");

                    b.Property<long>("UltimaSerie")
                        .HasColumnType("bigint")
                        .HasColumnName("ultima_serie");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ux_configuracion_logistica_empresa");

                    b.ToTable("configuracion", "logistica");
                });

            modelBuilder.Entity("AlxorCore.Logistica.Dominio.FichaLogistica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AltoCajaMm")
                        .HasColumnType("integer")
                        .HasColumnName("alto_caja_mm");

                    b.Property<int?>("AlturaMaxPaleMm")
                        .HasColumnType("integer")
                        .HasColumnName("altura_max_pale_mm");

                    b.Property<int?>("AnchoCajaMm")
                        .HasColumnType("integer")
                        .HasColumnName("ancho_caja_mm");

                    b.Property<int?>("CajasPorCapa")
                        .HasColumnType("integer")
                        .HasColumnName("cajas_por_capa");

                    b.Property<int?>("Capas")
                        .HasColumnType("integer")
                        .HasColumnName("capas");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("GestionLotes")
                        .HasColumnType("boolean")
                        .HasColumnName("gestion_lotes");

                    b.Property<string>("Gtin")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("gtin");

                    b.Property<string>("GtinCaja")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("gtin_caja");

                    b.Property<int?>("LargoCajaMm")
                        .HasColumnType("integer")
                        .HasColumnName("largo_caja_mm");

                    b.Property<decimal?>("PesoBrutoCajaKg")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("peso_bruto_caja_kg");

                    b.Property<decimal?>("PesoMaxPaleKg")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("peso_max_pale_kg");

                    b.Property<decimal?>("PesoNetoUnidadKg")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("peso_neto_unidad_kg");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<bool>("Remontable")
                        .HasColumnType("boolean")
                        .HasColumnName("remontable");

                    b.Property<Guid?>("SoporteId")
                        .HasColumnType("uuid")
                        .HasColumnName("soporte_id");

                    b.Property<int?>("TemperaturaMaxC")
                        .HasColumnType("integer")
                        .HasColumnName("temperatura_max_c");

                    b.Property<int?>("TemperaturaMinC")
                        .HasColumnType("integer")
                        .HasColumnName("temperatura_min_c");

                    b.Property<int>("UnidadesPorCaja")
                        .HasColumnType("integer")
                        .HasColumnName("unidades_por_caja");

                    b.Property<int?>("VidaMinimaEntregaDias")
                        .HasColumnType("integer")
                        .HasColumnName("vida_minima_entrega_dias");

                    b.Property<int?>("VidaUtilDias")
                        .HasColumnType("integer")
                        .HasColumnName("vida_util_dias");

                    b.HasKey("Id");

                    b.HasIndex("SoporteId")
                        .HasDatabaseName("ix_ficha_logistica_soporte");

                    b.HasIndex("EmpresaId", "Gtin")
                        .HasDatabaseName("ix_ficha_logistica_gtin");

                    b.HasIndex("EmpresaId", "GtinCaja")
                        .HasDatabaseName("ix_ficha_logistica_gtin_caja");

                    b.HasIndex("EmpresaId", "ProductoId")
                        .IsUnique()
                        .HasDatabaseName("ux_ficha_logistica_producto");

                    b.ToTable("ficha_logistica", "logistica");
                });

            modelBuilder.Entity("AlxorCore.Logistica.Dominio.PlantillaPaletizado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<int?>("AlturaMaxMm")
                        .HasColumnType("integer")
                        .HasColumnName("altura_max_mm");

                    b.Property<int>("CajasPorCapa")
                        .HasColumnType("integer")
                        .HasColumnName("cajas_por_capa");

                    b.Property<int>("Capas")
                        .HasColumnType("integer")
                        .HasColumnName("capas");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Instrucciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("instrucciones");

                    b.Property<decimal?>("PesoMaxKg")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("peso_max_kg");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<Guid>("SoporteId")
                        .HasColumnType("uuid")
                        .HasColumnName("soporte_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_plantilla_paletizado_cliente");

                    b.HasIndex("SoporteId")
                        .HasDatabaseName("ix_plantilla_paletizado_soporte");

                    b.HasIndex("EmpresaId", "ProductoId")
                        .HasDatabaseName("ix_plantilla_paletizado_producto");

                    b.ToTable("plantilla_paletizado", "logistica");
                });

            modelBuilder.Entity("AlxorCore.Logistica.Dominio.TipoSoporte", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("AltoMm")
                        .HasColumnType("integer")
                        .HasColumnName("alto_mm");

                    b.Property<int>("AnchoMm")
                        .HasColumnType("integer")
                        .HasColumnName("ancho_mm");

                    b.Property<decimal?>("CargaMaxKg")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("carga_max_kg");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid?>("EnvaseProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("envase_producto_id");

                    b.Property<int>("LargoMm")
                        .HasColumnType("integer")
                        .HasColumnName("largo_mm");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("TaraKg")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("tara_kg");

                    b.HasKey("Id");

                    b.HasIndex("EnvaseProductoId")
                        .HasDatabaseName("ix_tipo_soporte_envase");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_tipo_soporte_codigo");

                    b.ToTable("tipo_soporte", "logistica");
                });

            modelBuilder.Entity("AlxorCore.Logistica.Dominio.UnidadLogistica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<int?>("AlturaMm")
                        .HasColumnType("integer")
                        .HasColumnName("altura_mm");

                    b.Property<int?>("CajasCompleta")
                        .HasColumnType("integer")
                        .HasColumnName("cajas_completa");

                    b.Property<DateTimeOffset?>("CerradaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cerrada_en");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaExpedicion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_expedicion");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo_anulacion");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<Guid?>("OrdenFabricacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("orden_fabricacion_id");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origen");

                    b.Property<Guid?>("PadreId")
                        .HasColumnType("uuid")
                        .HasColumnName("padre_id");

                    b.Property<Guid?>("PedidoVentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_venta_id");

                    b.Property<decimal>("PesoBrutoKg")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("peso_bruto_kg");

                    b.Property<Guid?>("PlantillaId")
                        .HasColumnType("uuid")
                        .HasColumnName("plantilla_id");

                    b.Property<string>("ReferenciaExpedicion")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("referencia_expedicion");

                    b.Property<Guid?>("SoporteId")
                        .HasColumnType("uuid")
                        .HasColumnName("soporte_id");

                    b.Property<string>("Sscc")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("sscc");

                    b.Property<decimal>("TaraKg")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("tara_kg");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UbicacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ubicacion_id");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId")
                        .HasDatabaseName("ix_unidad_logistica_almacen");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_unidad_logistica_cliente");

                    b.HasIndex("OrdenFabricacionId")
                        .HasDatabaseName("ix_unidad_logistica_orden");

                    b.HasIndex("PadreId")
                        .HasDatabaseName("ix_unidad_logistica_padre");

                    b.HasIndex("PedidoVentaId")
                        .HasDatabaseName("ix_unidad_logistica_pedido");

                    b.HasIndex("PlantillaId")
                        .HasDatabaseName("ix_unidad_logistica_plantilla");

                    b.HasIndex("SoporteId")
                        .HasDatabaseName("ix_unidad_logistica_soporte");

                    b.HasIndex("UbicacionId")
                        .HasDatabaseName("ix_unidad_logistica_ubicacion");

                    b.HasIndex("EmpresaId", "Sscc")
                        .IsUnique()
                        .HasDatabaseName("ux_unidad_logistica_sscc");

                    b.HasIndex("EmpresaId", "Estado", "AlmacenId")
                        .HasDatabaseName("ix_unidad_logistica_estado");

                    b.ToTable("unidad_logistica", "logistica");
                });

            modelBuilder.Entity("AlxorCore.Logistica.Dominio.UnidadLogistica", b =>
                {
                    b.OwnsMany("AlxorCore.Logistica.Dominio.LineaUnidadLogistica", "Contenido", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Cajas")
                                .HasColumnType("integer")
                                .HasColumnName("cajas");

                            b1.Property<DateOnly?>("FechaCaducidad")
                                .HasColumnType("date")
                                .HasColumnName("fecha_caducidad");

                            b1.Property<string>("Lote")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("lote");

                            b1.Property<decimal>("PesoBrutoKg")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("peso_bruto_kg");

                            b1.Property<decimal>("PesoNetoKg")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("peso_neto_kg");

                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("producto_id");

                            b1.Property<decimal>("Unidades")
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("unidades");

                            b1.Property<Guid>("unidad_logistica_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("unidad_logistica_id");

                            b1.HasIndex("ProductoId", "Lote")
                                .HasDatabaseName("ix_linea_unidad_logistica_producto");

                            b1.ToTable("linea_unidad_logistica", "logistica");

                            b1.WithOwner()
                                .HasForeignKey("unidad_logistica_id");
                        });

                    b.Navigation("Contenido");
                });
#pragma warning restore 612, 618
        }
    }
}
