// <auto-generated />
using System;
using AlxorCore.Cooperativa.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Cooperativa.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(CooperativaDbContext))]
    [Migration("20260929211434_InicialCooperativa")]
    partial class InicialCooperativa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cooperativa")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Cooperativa.Dominio.Acta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acuerdos")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("acuerdos");

                    b.Property<DateTimeOffset?>("AprobadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aprobada_en");

                    b.Property<string>("Caracter")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("caracter");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Lugar")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lugar");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("OrdenDelDia")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("orden_del_dia");

                    b.Property<string>("Organo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("organo");

                    b.Property<int>("Presentes")
                        .HasColumnType("integer")
                        .HasColumnName("presentes");

                    b.Property<string>("Presidente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("presidente");

                    b.Property<int>("Representados")
                        .HasColumnType("integer")
                        .HasColumnName("representados");

                    b.Property<string>("Secretario")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("secretario");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Organo", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_acta_numero")
                        .HasFilter("numero IS NOT NULL");

                    b.ToTable("acta", "cooperativa");
                });

            modelBuilder.Entity("AlxorCore.Cooperativa.Dominio.ConfiguracionCooperativa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AportacionObligatoria")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("aportacion_obligatoria");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("base_retorno");

                    b.Property<bool>("Contabilizar")
                        .HasColumnType("boolean")
                        .HasColumnName("contabilizar");

                    b.Property<decimal>("DeduccionMaximaExpulsion")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("deduccion_maxima_expulsion");

                    b.Property<decimal>("DeduccionMaximaNoJustificada")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("deduccion_maxima_no_justificada");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("forma");

                    b.Property<decimal>("InteresMaximoCapital")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("interes_maximo_capital");

                    b.Property<decimal>("PorcentajeFepMinimo")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("porcentaje_fep_minimo");

                    b.Property<decimal>("PorcentajeFroMinimo")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("porcentaje_fro_minimo");

                    b.Property<decimal>("PorcentajeRetencion")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("porcentaje_retencion");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ux_configuracion_cooperativa_empresa");

                    b.ToTable("configuracion", "cooperativa");
                });

            modelBuilder.Entity("AlxorCore.Cooperativa.Dominio.MovimientoCapital", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnulaId")
                        .HasColumnType("uuid")
                        .HasColumnName("anula_id");

                    b.Property<Guid?>("AsientoId")
                        .HasColumnType("uuid")
                        .HasColumnName("asiento_id");

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("clase");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("concepto");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<decimal>("Deduccion")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("deduccion");

                    b.Property<decimal>("Desembolsado")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("desembolsado");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<Guid?>("RepartoId")
                        .HasColumnType("uuid")
                        .HasColumnName("reparto_id");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("socio_id");

                    b.Property<decimal>("Suscrito")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("suscrito");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("AnulaId")
                        .IsUnique()
                        .HasDatabaseName("ux_movimiento_capital_anula")
                        .HasFilter("anula_id IS NOT NULL");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_movimiento_capital_grupo");

                    b.HasIndex("RepartoId")
                        .HasDatabaseName("ix_movimiento_capital_reparto");

                    b.HasIndex("SocioId", "Fecha")
                        .HasDatabaseName("ix_movimiento_capital_socio");

                    b.ToTable("movimiento_capital", "cooperativa");
                });

            modelBuilder.Entity("AlxorCore.Cooperativa.Dominio.Reparto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AsientoId")
                        .HasColumnType("uuid")
                        .HasColumnName("asiento_id");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("base_retorno");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<decimal>("Excedente")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("excedente");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateOnly?>("FechaAsamblea")
                        .HasColumnType("date")
                        .HasColumnName("fecha_asamblea");

                    b.Property<decimal>("ImporteFep")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("importe_fep");

                    b.Property<decimal>("ImporteFro")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("importe_fro");

                    b.Property<decimal>("ImporteIntereses")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("importe_intereses");

                    b.Property<decimal>("ImporteRetorno")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("importe_retorno");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo_anulacion");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("PorcentajeFep")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("porcentaje_fep");

                    b.Property<decimal>("PorcentajeFro")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("porcentaje_fro");

                    b.Property<decimal>("PorcentajeIntereses")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("porcentaje_intereses");

                    b.Property<decimal>("PorcentajeRetencion")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("porcentaje_retencion");

                    b.Property<decimal>("ReservasVoluntarias")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("reservas_voluntarias");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Ejercicio")
                        .IsUnique()
                        .HasDatabaseName("ux_reparto_ejercicio_vivo")
                        .HasFilter("estado <> 'Anulado'");

                    b.ToTable("reparto", "cooperativa");
                });

            modelBuilder.Entity("AlxorCore.Cooperativa.Dominio.Socio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("FechaAlta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_alta");

                    b.Property<DateOnly?>("FechaBaja")
                        .HasColumnType("date")
                        .HasColumnName("fecha_baja");

                    b.Property<string>("MotivoBaja")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("motivo_baja");

                    b.Property<string>("Nif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_socio_proveedor");

                    b.HasIndex("EmpresaId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_socio_numero");

                    b.HasIndex("EmpresaId", "ProveedorId")
                        .IsUnique()
                        .HasDatabaseName("ux_socio_proveedor_activo")
                        .HasFilter("fecha_baja IS NULL");

                    b.ToTable("socio", "cooperativa");
                });

            modelBuilder.Entity("AlxorCore.Cooperativa.Dominio.ConfiguracionCooperativa", b =>
                {
                    b.OwnsOne("AlxorCore.Cooperativa.Dominio.CuentasCooperativa", "Cuentas", b1 =>
                        {
                            b1.Property<Guid>("ConfiguracionCooperativaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Capital")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("cuenta_capital");

                            b1.Property<string>("DesembolsosPendientes")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("cuenta_desembolsos_pendientes");

                            b1.Property<string>("Fep")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("cuenta_fep");

                            b1.Property<string>("Fro")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("cuenta_fro");

                            b1.Property<string>("Reembolsos")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("cuenta_reembolsos");

                            b1.Property<string>("ReservasVoluntarias")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("cuenta_reservas_voluntarias");

                            b1.Property<string>("Resultado")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("cuenta_resultado");

                            b1.Property<string>("Retenciones")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("cuenta_retenciones");

                            b1.Property<string>("Retornos")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("cuenta_retornos");

                            b1.Property<string>("Tesoreria")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("cuenta_tesoreria");

                            b1.HasKey("ConfiguracionCooperativaId");

                            b1.ToTable("configuracion", "cooperativa");

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracionCooperativaId");
                        });

                    b.Navigation("Cuentas")
                        .IsRequired();
                });

            modelBuilder.Entity("AlxorCore.Cooperativa.Dominio.MovimientoCapital", b =>
                {
                    b.HasOne("AlxorCore.Cooperativa.Dominio.Socio", null)
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimiento_capital_socio");
                });

            modelBuilder.Entity("AlxorCore.Cooperativa.Dominio.Reparto", b =>
                {
                    b.OwnsMany("AlxorCore.Cooperativa.Dominio.LineaReparto", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Actividad")
                                .HasColumnType("numeric(16,3)")
                                .HasColumnName("actividad");

                            b1.Property<decimal>("Capital")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("capital");

                            b1.Property<decimal>("Capitalizado")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("capitalizado");

                            b1.Property<decimal>("Intereses")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("intereses");

                            b1.Property<decimal>("Neto")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("neto");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("nombre");

                            b1.Property<int>("Numero")
                                .HasColumnType("integer")
                                .HasColumnName("numero");

                            b1.Property<decimal>("Retencion")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("retencion");

                            b1.Property<decimal>("Retorno")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("retorno");

                            b1.Property<Guid>("SocioId")
                                .HasColumnType("uuid")
                                .HasColumnName("socio_id");

                            b1.Property<Guid>("reparto_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("SocioId")
                                .HasDatabaseName("ix_linea_reparto_socio");

                            b1.HasIndex("reparto_id", "SocioId")
                                .IsUnique()
                                .HasDatabaseName("ux_linea_reparto_socio");

                            b1.ToTable("linea_reparto", "cooperativa");

                            b1.WithOwner()
                                .HasForeignKey("reparto_id");
                        });

                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
