// <auto-generated />
using System;
using AlxorCore.Inventario.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Inventario.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(InventarioDbContext))]
    [Migration("20260821231408_MigracionInicialInventario")]
    partial class MigracionInicialInventario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventario")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Inventario.Dominio.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_almacen_empresa_codigo");

                    b.ToTable("almacen", "inventario");
                });

            modelBuilder.Entity("AlxorCore.Inventario.Dominio.Existencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<Guid?>("UbicacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ubicacion_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ProductoId", "AlmacenId", "UbicacionId")
                        .HasDatabaseName("ix_existencia_clave");

                    b.ToTable("existencia", "inventario");
                });

            modelBuilder.Entity("AlxorCore.Inventario.Dominio.MovimientoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("cantidad");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<string>("Referencia")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("referencia");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UbicacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ubicacion_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ProductoId")
                        .HasDatabaseName("ix_movimiento_empresa_producto");

                    b.ToTable("movimiento_inventario", "inventario");
                });

            modelBuilder.Entity("AlxorCore.Inventario.Dominio.Ubicacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "AlmacenId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_ubicacion_almacen_codigo");

                    b.ToTable("ubicacion", "inventario");
                });

            modelBuilder.Entity("AlxorCore.Inventario.Dominio.UbicacionDefecto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<Guid?>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<Guid>("UbicacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ubicacion_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ProductoId", "AlmacenId", "ProveedorId")
                        .HasDatabaseName("ix_ubidef_clave");

                    b.ToTable("ubicacion_defecto", "inventario");
                });
#pragma warning restore 612, 618
        }
    }
}
