// <auto-generated />
using System;
using AlxorCore.Migracion.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Migracion.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(MigracionDbContext))]
    partial class MigracionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("migracion")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Migracion.Dominio.Correspondencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("DestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("destino_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entidad");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origen");

                    b.Property<string>("OrigenId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("origen_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "DestinoId")
                        .HasDatabaseName("ix_correspondencia_destino");

                    b.HasIndex("EmpresaId", "Origen", "Entidad", "OrigenId")
                        .IsUnique()
                        .HasDatabaseName("ux_correspondencia_origen");

                    b.ToTable("correspondencia", "migracion");
                });

            modelBuilder.Entity("AlxorCore.Migracion.Dominio.EjecucionMigracion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("FechaCorte")
                        .HasColumnType("date")
                        .HasColumnName("fecha_corte");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origen");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resumen");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "CreadoEn")
                        .HasDatabaseName("ix_ejecucion_empresa");

                    b.ToTable("ejecucion", "migracion");
                });
#pragma warning restore 612, 618
        }
    }
}
