// <auto-generated />
using System;
using AlxorCore.Gastos.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Gastos.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(GastosDbContext))]
    [Migration("20260927205404_DuaImportacion")]
    partial class DuaImportacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gastos")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Gastos.Dominio.DuaImportacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aduana")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("aduana");

                    b.Property<decimal>("Aranceles")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("aranceles");

                    b.Property<decimal>("BaseIva")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_iva");

                    b.Property<decimal>("CuotaIva")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("cuota_iva");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("FechaAdmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_admision");

                    b.Property<Guid>("GastoId")
                        .HasColumnType("uuid")
                        .HasColumnName("gasto_id");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("mrn");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("GastoId")
                        .HasDatabaseName("ix_dua_importacion_gasto");

                    b.HasIndex("EmpresaId", "Mrn")
                        .IsUnique()
                        .HasDatabaseName("ux_dua_importacion_empresa_mrn");

                    b.ToTable("dua_importacion", "gastos");
                });

            modelBuilder.Entity("AlxorCore.Gastos.Dominio.Gasto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActividadNegocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("actividad_negocio_id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Afectacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Comun")
                        .HasColumnName("afectacion");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_imponible");

                    b.Property<string>("CodigoIva")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_iva");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("concepto");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<decimal>("CuotaIva")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("cuota_iva");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("PorcentajeIrpf")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_irpf");

                    b.Property<decimal>("PorcentajeIva")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_iva");

                    b.Property<Guid?>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("ProveedorTexto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("proveedor_texto");

                    b.Property<decimal>("RetencionIrpf")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("retencion_irpf");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Fecha")
                        .HasDatabaseName("ix_gasto_empresa_fecha");

                    b.ToTable("gasto", "gastos");
                });

            modelBuilder.Entity("AlxorCore.Gastos.Dominio.MensajeSalida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Carga")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("carga");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos");

                    b.Property<bool>("Procesado")
                        .HasColumnType("boolean")
                        .HasColumnName("procesado");

                    b.Property<DateTimeOffset?>("ProcesadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesado_en");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ultimo_error");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Procesado")
                        .HasDatabaseName("ix_mensaje_salida_empresa_procesado");

                    b.ToTable("mensaje_salida", "gastos");
                });
#pragma warning restore 612, 618
        }
    }
}
