// <auto-generated />
using System;
using AlxorCore.Tesoreria.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Tesoreria.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(TesoreriaDbContext))]
    [Migration("20260926193521_GarantiasTesoreria")]
    partial class GarantiasTesoreria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tesoreria")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Tesoreria.Dominio.Anticipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("concepto");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("importe");

                    b.Property<string>("Metodo")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("metodo");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ClienteId")
                        .HasDatabaseName("ix_anticipo_empresa_cliente");

                    b.ToTable("anticipo", "tesoreria");
                });

            modelBuilder.Entity("AlxorCore.Tesoreria.Dominio.ConfiguracionReclamaciones", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Niveles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("niveles");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ux_configuracion_reclamaciones_empresa");

                    b.ToTable("configuracion_reclamaciones", "tesoreria");
                });

            modelBuilder.Entity("AlxorCore.Tesoreria.Dominio.Movimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("importe");

                    b.Property<string>("Metodo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("metodo");

                    b.Property<string>("Sentido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sentido");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "TipoDocumento", "DocumentoId")
                        .HasDatabaseName("ix_movimiento_documento");

                    b.ToTable("movimiento", "tesoreria");
                });

            modelBuilder.Entity("AlxorCore.Tesoreria.Dominio.PrevisionTesoreria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("concepto");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("importe");

                    b.Property<string>("Sentido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sentido");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Fecha")
                        .HasDatabaseName("ix_prevision_empresa_fecha");

                    b.ToTable("prevision", "tesoreria");
                });

            modelBuilder.Entity("AlxorCore.Tesoreria.Dominio.Reclamacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<int>("DiasRetraso")
                        .HasColumnType("integer")
                        .HasColumnName("dias_retraso");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("factura_id");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Nota")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nota");

                    b.Property<decimal>("Pendiente")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("pendiente");

                    b.Property<DateTimeOffset>("RealizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("realizada_en");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "FacturaId")
                        .HasDatabaseName("ix_reclamacion_empresa_factura");

                    b.ToTable("reclamacion", "tesoreria");
                });

            modelBuilder.Entity("AlxorCore.Tesoreria.Dominio.Anticipo", b =>
                {
                    b.OwnsMany("AlxorCore.Tesoreria.Dominio.AplicacionAnticipo", "Aplicaciones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("FacturaId")
                                .HasColumnType("uuid")
                                .HasColumnName("factura_id");

                            b1.Property<DateOnly>("Fecha")
                                .HasColumnType("date")
                                .HasColumnName("fecha");

                            b1.Property<decimal>("Importe")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("importe");

                            b1.Property<Guid>("MovimientoId")
                                .HasColumnType("uuid")
                                .HasColumnName("movimiento_id");

                            b1.Property<Guid>("anticipo_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("MovimientoId")
                                .IsUnique()
                                .HasDatabaseName("ux_aplicacion_anticipo_movimiento");

                            b1.HasIndex("anticipo_id")
                                .HasDatabaseName("ix_aplicacion_anticipo_anticipo");

                            b1.ToTable("aplicacion_anticipo", "tesoreria");

                            b1.WithOwner()
                                .HasForeignKey("anticipo_id");
                        });

                    b.Navigation("Aplicaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
