// <auto-generated />
using System;
using AlxorCore.Organizacion.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Organizacion.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(OrganizacionDbContext))]
    [Migration("20260823080401_ActividadesNegocio")]
    partial class ActividadesNegocio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organizacion")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Organizacion.Dominio.ActividadNegocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_actividad_negocio_grupo");

                    b.ToTable("actividad_negocio", "organizacion");
                });

            modelBuilder.Entity("AlxorCore.Organizacion.Dominio.AsignacionSerie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ambito");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefijo");

                    b.Property<Guid>("TerceroId")
                        .HasColumnType("uuid")
                        .HasColumnName("tercero_id");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "TipoDocumento", "Ambito", "TerceroId")
                        .IsUnique()
                        .HasDatabaseName("ux_asignacion_serie");

                    b.ToTable("asignacion_serie", "organizacion");
                });

            modelBuilder.Entity("AlxorCore.Organizacion.Dominio.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("ColorPrincipal")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_principal");

                    b.Property<string>("ControlRiesgo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("control_riesgo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("EmailContacto")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_contacto");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Iban")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("iban");

                    b.Property<string>("IdentificadorAcreedor")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("identificador_acreedor");

                    b.Property<byte[]>("LogoPng")
                        .HasColumnType("bytea")
                        .HasColumnName("logo_png");

                    b.Property<string>("MetodoValoracion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("metodo_valoracion");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("pais");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razon_social");

                    b.Property<string>("RegimenIva")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("regimen_iva");

                    b.Property<string>("Telefono")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("telefono");

                    b.Property<string>("TextoPie")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("texto_pie");

                    b.Property<string>("Web")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("web");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_empresa_grupo");

                    b.HasIndex("Nif")
                        .IsUnique()
                        .HasDatabaseName("ux_empresa_nif");

                    b.ToTable("empresa", "organizacion");
                });

            modelBuilder.Entity("AlxorCore.Organizacion.Dominio.FormaPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("DiasVencimiento")
                        .HasColumnType("integer")
                        .HasColumnName("dias_vencimiento");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("GeneraVencimiento")
                        .HasColumnType("boolean")
                        .HasColumnName("genera_vencimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<bool>("RegistrarPagoAutomatico")
                        .HasColumnType("boolean")
                        .HasColumnName("registrar_pago_automatico");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_forma_pago_empresa");

                    b.ToTable("forma_pago", "organizacion");
                });

            modelBuilder.Entity("AlxorCore.Organizacion.Dominio.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("grupo", "organizacion");
                });

            modelBuilder.Entity("AlxorCore.Organizacion.Dominio.Membresia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("RolCodigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rol_codigo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ux_membresia_usuario_empresa");

                    b.ToTable("membresia", "organizacion");
                });

            modelBuilder.Entity("AlxorCore.Organizacion.Dominio.SerieNumeracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefijo");

                    b.Property<long>("SiguienteNumero")
                        .HasColumnType("bigint")
                        .HasColumnName("siguiente_numero");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "TipoDocumento", "Ejercicio", "Prefijo")
                        .IsUnique()
                        .HasDatabaseName("ux_serie_empresa_tipo_ejercicio_prefijo");

                    b.ToTable("serie_numeracion", "organizacion");
                });

            modelBuilder.Entity("AlxorCore.Organizacion.Dominio.VisibilidadActividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActividadNegocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("actividad_negocio_id");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("area");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Area")
                        .HasDatabaseName("ix_visibilidad_usuario_area");

                    b.HasIndex("GrupoId", "UsuarioId", "Area", "ActividadNegocioId")
                        .IsUnique()
                        .HasDatabaseName("ux_visibilidad_grupo_usuario_area_actividad");

                    b.ToTable("visibilidad_actividad", "organizacion");
                });

            modelBuilder.Entity("AlxorCore.Organizacion.Dominio.Empresa", b =>
                {
                    b.OwnsOne("AlxorCore.Nucleo.Comun.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("direccion_calle");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("direccion_cp");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("direccion_pais");

                            b1.Property<string>("Poblacion")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("direccion_poblacion");

                            b1.Property<string>("Provincia")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("direccion_provincia");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("empresa", "organizacion");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
