// <auto-generated />
using System;
using AlxorCore.Contabilidad.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Contabilidad.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContabilidadDbContext))]
    [Migration("20260822123701_ContabilizacionDiferida")]
    partial class ContabilizacionDiferida
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contabilidad")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.Asiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("concepto");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origen");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Ejercicio", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_asiento_empresa_ejercicio_numero");

                    b.ToTable("asiento", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.ConfiguracionContabilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ContabilizacionAutomatica")
                        .HasColumnType("boolean")
                        .HasColumnName("contabilizacion_automatica");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modo");

                    b.HasKey("Id");

                    b.ToTable("config_contabilidad", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Grupo")
                        .HasColumnType("integer")
                        .HasColumnName("grupo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_cuenta_empresa_codigo");

                    b.ToTable("cuenta", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.DocumentoPendiente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AsientoId")
                        .HasColumnType("uuid")
                        .HasColumnName("asiento_id");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_imponible");

                    b.Property<string>("CodigoIva")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_iva");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<decimal>("CuotaIva")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("cuota_iva");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Familia")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("familia");

                    b.Property<DateOnly>("FechaDocumento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_documento");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date")
                        .HasColumnName("fecha_registro");

                    b.Property<Guid>("OrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("origen_id");

                    b.Property<string>("OrigenTipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("origen_tipo");

                    b.Property<decimal>("PorcentajeIrpf")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_irpf");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("referencia");

                    b.Property<decimal>("RetencionIrpf")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("retencion_irpf");

                    b.Property<string>("Sentido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sentido");

                    b.Property<Guid?>("TerceroId")
                        .HasColumnType("uuid")
                        .HasColumnName("tercero_id");

                    b.Property<string>("TerceroNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tercero_nombre");

                    b.Property<string>("TipoTercero")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tipo_tercero");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Estado")
                        .HasDatabaseName("ix_documento_pendiente_empresa_estado");

                    b.ToTable("documento_pendiente", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.Asiento", b =>
                {
                    b.OwnsMany("AlxorCore.Contabilidad.Dominio.Apunte", "Apuntes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Concepto")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("concepto");

                            b1.Property<string>("CuentaCodigo")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("cuenta_codigo");

                            b1.Property<decimal>("Debe")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("debe");

                            b1.Property<decimal>("Haber")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("haber");

                            b1.Property<Guid>("asiento_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("asiento_id");

                            b1.ToTable("apunte", "contabilidad");

                            b1.WithOwner()
                                .HasForeignKey("asiento_id");
                        });

                    b.Navigation("Apuntes");
                });
#pragma warning restore 612, 618
        }
    }
}
