// <auto-generated />
using System;
using System.Collections.Generic;
using AlxorCore.Contabilidad.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Contabilidad.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContabilidadDbContext))]
    [Migration("20260929093857_BienesInversionProrrata")]
    partial class BienesInversionProrrata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contabilidad")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.Asiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnulaAsientoId")
                        .HasColumnType("uuid")
                        .HasColumnName("anula_asiento_id");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("concepto");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Diario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("diario");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origen");

                    b.HasKey("Id");

                    b.HasIndex("AnulaAsientoId")
                        .IsUnique()
                        .HasDatabaseName("ux_asiento_anula")
                        .HasFilter("anula_asiento_id IS NOT NULL");

                    b.HasIndex("EmpresaId", "Ejercicio", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_asiento_empresa_ejercicio_numero");

                    b.HasIndex("EmpresaId", "Ejercicio", "Diario", "Numero")
                        .HasDatabaseName("ix_asiento_diario");

                    b.ToTable("asiento", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.CentroAnalitico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<Guid?>("PadreId")
                        .HasColumnType("uuid")
                        .HasColumnName("padre_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("PadreId");

                    b.HasIndex("GrupoId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_centro_analitico_grupo_codigo");

                    b.ToTable("centro_analitico", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.ClaveReparto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_clave_reparto_grupo_codigo");

                    b.ToTable("clave_reparto", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.ConfiguracionContabilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CerradoHasta")
                        .HasColumnType("date")
                        .HasColumnName("cerrado_hasta");

                    b.Property<bool>("ContabilizacionAutomatica")
                        .HasColumnType("boolean")
                        .HasColumnName("contabilizacion_automatica");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("LongitudSubcuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(8)
                        .HasColumnName("longitud_subcuenta");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modo");

                    b.HasKey("Id");

                    b.ToTable("config_contabilidad", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Grupo")
                        .HasColumnType("integer")
                        .HasColumnName("grupo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<Guid?>("TerceroId")
                        .HasColumnType("uuid")
                        .HasColumnName("tercero_id");

                    b.Property<string>("TipoTercero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_tercero");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_cuenta_empresa_codigo");

                    b.HasIndex("EmpresaId", "TerceroId")
                        .HasDatabaseName("ix_cuenta_empresa_tercero");

                    b.ToTable("cuenta", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.DiarioContable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<List<string>>("_origenes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("origenes");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_diario_empresa_codigo");

                    b.ToTable("diario_contable", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.DocumentoPendiente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActividadNegocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("actividad_negocio_id");

                    b.Property<string>("Afectacion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("afectacion");

                    b.Property<bool>("Anulacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("anulacion");

                    b.Property<Guid?>("AsientoId")
                        .HasColumnType("uuid")
                        .HasColumnName("asiento_id");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_imponible");

                    b.Property<string>("CodigoIva")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_iva");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CuentaTercero")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cuenta_tercero");

                    b.Property<string>("CuentaTesoreria")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cuenta_tesoreria");

                    b.Property<decimal>("CuotaIva")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("cuota_iva");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Familia")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("familia");

                    b.Property<DateOnly>("FechaDocumento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_documento");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Lineas")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("lineas")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid>("OrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("origen_id");

                    b.Property<string>("OrigenTipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("origen_tipo");

                    b.Property<decimal>("PorcentajeIrpf")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_irpf");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("referencia");

                    b.Property<decimal>("RetencionIrpf")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("retencion_irpf");

                    b.Property<string>("Sentido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sentido");

                    b.Property<Guid?>("TerceroId")
                        .HasColumnType("uuid")
                        .HasColumnName("tercero_id");

                    b.Property<string>("TerceroNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tercero_nombre");

                    b.Property<string>("TipoTercero")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tipo_tercero");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Estado")
                        .HasDatabaseName("ix_documento_pendiente_empresa_estado");

                    b.ToTable("documento_pendiente", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.EjecucionAnalitica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CentroOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("centro_origen_id");

                    b.Property<Guid?>("ClaveRepartoId")
                        .HasColumnType("uuid")
                        .HasColumnName("clave_reparto_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("CentroOrigenId");

                    b.HasIndex("ClaveRepartoId");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_ejecucion_analitica_empresa");

                    b.ToTable("ejecucion_analitica", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.ImputacionAnalitica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApunteId")
                        .HasColumnType("uuid")
                        .HasColumnName("apunte_id");

                    b.Property<Guid?>("AsientoId")
                        .HasColumnType("uuid")
                        .HasColumnName("asiento_id");

                    b.Property<Guid>("CentroId")
                        .HasColumnType("uuid")
                        .HasColumnName("centro_id");

                    b.Property<string>("CuentaCodigo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cuenta_codigo");

                    b.Property<Guid?>("EjecucionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejecucion_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("importe");

                    b.Property<string>("Naturaleza")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("naturaleza");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("origen");

                    b.Property<Guid?>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.HasKey("Id");

                    b.HasIndex("ApunteId")
                        .HasDatabaseName("ix_imputacion_analitica_apunte");

                    b.HasIndex("AsientoId")
                        .HasDatabaseName("ix_imputacion_analitica_asiento");

                    b.HasIndex("CentroId");

                    b.HasIndex("EjecucionId");

                    b.HasIndex("PartidaId");

                    b.HasIndex("EmpresaId", "Fecha")
                        .HasDatabaseName("ix_imputacion_analitica_empresa_fecha");

                    b.ToTable("imputacion_analitica", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.Inmovilizado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BienInmueble")
                        .HasColumnType("boolean")
                        .HasColumnName("bien_inmueble");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("CuentaActivo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cuenta_activo");

                    b.Property<string>("CuentaAmortizacion")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cuenta_amortizacion");

                    b.Property<string>("CuentaDotacion")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cuenta_dotacion");

                    b.Property<decimal?>("CuotaImpuestoSoportada")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("cuota_impuesto_soportada");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaAdquisicion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_adquisicion");

                    b.Property<DateOnly>("FechaAlta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_alta");

                    b.Property<DateOnly?>("FechaBaja")
                        .HasColumnType("date")
                        .HasColumnName("fecha_baja");

                    b.Property<string>("Periodicidad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("periodicidad");

                    b.Property<int?>("PorcentajeDeduccionInicial")
                        .HasColumnType("integer")
                        .HasColumnName("porcentaje_deduccion_inicial");

                    b.Property<decimal>("ValorAdquisicion")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_adquisicion");

                    b.Property<decimal?>("ValorEnajenacion")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_enajenacion");

                    b.Property<decimal>("ValorResidual")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_residual");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_inmovilizado_empresa_codigo");

                    b.ToTable("inmovilizado", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.PartidaAnalitica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Naturaleza")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("naturaleza");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<Guid?>("PadreId")
                        .HasColumnType("uuid")
                        .HasColumnName("padre_id");

                    b.HasKey("Id");

                    b.HasIndex("PadreId");

                    b.HasIndex("GrupoId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_partida_analitica_grupo_codigo");

                    b.ToTable("partida_analitica", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.Periodificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AsientoCancelacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("asiento_cancelacion_id");

                    b.Property<Guid?>("AsientoReclasificacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("asiento_reclasificacion_id");

                    b.Property<string>("CuentaPeriodificacion")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cuenta_periodificacion");

                    b.Property<string>("CuentaResultado")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cuenta_resultado");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<int>("EjercicioInicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio_inicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("importe");

                    b.Property<int>("MesInicio")
                        .HasColumnType("integer")
                        .HasColumnName("mes_inicio");

                    b.Property<int>("Meses")
                        .HasColumnType("integer")
                        .HasColumnName("meses");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("AsientoCancelacionId")
                        .HasDatabaseName("ix_periodificacion_asiento_cancelacion");

                    b.HasIndex("AsientoReclasificacionId")
                        .HasDatabaseName("ix_periodificacion_asiento_reclasificacion");

                    b.HasIndex("EmpresaId", "Estado")
                        .HasDatabaseName("ix_periodificacion_empresa_estado");

                    b.ToTable("periodificacion", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.PeriodoAnalitico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Cerrado")
                        .HasColumnType("boolean")
                        .HasColumnName("cerrado");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_periodo_analitico_empresa_codigo");

                    b.ToTable("periodo_analitico", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.PlantillaAsiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Concepto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("concepto");

                    b.Property<string>("Diario")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("diario");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Lineas")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("lineas");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("OrigenTipo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("origen_tipo");

                    b.Property<string>("Sentido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sentido");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Sentido", "OrigenTipo")
                        .IsUnique()
                        .HasDatabaseName("ux_plantilla_asiento_sentido_origen");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("EmpresaId", "Sentido", "OrigenTipo"), false);

                    b.ToTable("plantilla_asiento", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.PresupuestoContable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<int>("Meses")
                        .HasColumnType("integer")
                        .HasColumnName("meses");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_presupuesto_contable_empresa_codigo");

                    b.ToTable("presupuesto_contable", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.ReglaAnalitica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActividadNegocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("actividad_negocio_id");

                    b.Property<Guid?>("CentroId")
                        .HasColumnType("uuid")
                        .HasColumnName("centro_id");

                    b.Property<Guid?>("ClaveRepartoId")
                        .HasColumnType("uuid")
                        .HasColumnName("clave_reparto_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Familia")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("familia");

                    b.Property<Guid?>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.Property<string>("PrefijoCuenta")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("prefijo_cuenta");

                    b.Property<int>("Prioridad")
                        .HasColumnType("integer")
                        .HasColumnName("prioridad");

                    b.Property<Guid?>("TerceroId")
                        .HasColumnType("uuid")
                        .HasColumnName("tercero_id");

                    b.Property<DateOnly?>("VigenteDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigente_desde");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigente_hasta");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("ClaveRepartoId");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_regla_analitica_empresa");

                    b.HasIndex("PartidaId");

                    b.ToTable("regla_analitica", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.ReglaContabilizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CuentaCodigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cuenta_codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Familia")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("familia");

                    b.Property<string>("Sentido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sentido");

                    b.Property<string>("TipoTercero")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tipo_tercero");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Sentido")
                        .HasDatabaseName("ix_regla_contabilizacion_empresa_sentido");

                    b.ToTable("regla_contabilizacion", "contabilidad");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.Asiento", b =>
                {
                    b.OwnsMany("AlxorCore.Contabilidad.Dominio.Apunte", "Apuntes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Concepto")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("concepto");

                            b1.Property<string>("CuentaCodigo")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("cuenta_codigo");

                            b1.Property<decimal>("Debe")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("debe");

                            b1.Property<decimal>("Haber")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("haber");

                            b1.Property<Guid>("asiento_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("asiento_id");

                            b1.ToTable("apunte", "contabilidad");

                            b1.WithOwner()
                                .HasForeignKey("asiento_id");
                        });

                    b.Navigation("Apuntes");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.CentroAnalitico", b =>
                {
                    b.HasOne("AlxorCore.Contabilidad.Dominio.CentroAnalitico", null)
                        .WithMany()
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.ClaveReparto", b =>
                {
                    b.OwnsMany("AlxorCore.Contabilidad.Dominio.LineaClaveReparto", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("CentroId")
                                .HasColumnType("uuid")
                                .HasColumnName("centro_id");

                            b1.Property<decimal>("Porcentaje")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("porcentaje");

                            b1.Property<Guid>("clave_reparto_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("CentroId");

                            b1.HasIndex("clave_reparto_id")
                                .HasDatabaseName("ix_linea_clave_reparto_clave");

                            b1.ToTable("linea_clave_reparto", "contabilidad");

                            b1.HasOne("AlxorCore.Contabilidad.Dominio.CentroAnalitico", null)
                                .WithMany()
                                .HasForeignKey("CentroId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("clave_reparto_id");
                        });

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.EjecucionAnalitica", b =>
                {
                    b.HasOne("AlxorCore.Contabilidad.Dominio.CentroAnalitico", null)
                        .WithMany()
                        .HasForeignKey("CentroOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlxorCore.Contabilidad.Dominio.ClaveReparto", null)
                        .WithMany()
                        .HasForeignKey("ClaveRepartoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.ImputacionAnalitica", b =>
                {
                    b.HasOne("AlxorCore.Contabilidad.Dominio.CentroAnalitico", null)
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlxorCore.Contabilidad.Dominio.EjecucionAnalitica", null)
                        .WithMany()
                        .HasForeignKey("EjecucionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlxorCore.Contabilidad.Dominio.PartidaAnalitica", null)
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.Inmovilizado", b =>
                {
                    b.OwnsOne("AlxorCore.Contabilidad.Dominio.PlanAmortizacion", "Contable", b1 =>
                        {
                            b1.Property<Guid>("InmovilizadoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Metodo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("metodo_contable");

                            b1.Property<decimal>("PorcentajeDegresivo")
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("porcentaje_degresivo_contable");

                            b1.Property<int>("VidaUtilAnios")
                                .HasColumnType("integer")
                                .HasColumnName("vida_util_contable");

                            b1.HasKey("InmovilizadoId");

                            b1.ToTable("inmovilizado", "contabilidad");

                            b1.WithOwner()
                                .HasForeignKey("InmovilizadoId");
                        });

                    b.OwnsOne("AlxorCore.Contabilidad.Dominio.PlanAmortizacion", "Fiscal", b1 =>
                        {
                            b1.Property<Guid>("InmovilizadoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Metodo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("metodo_fiscal");

                            b1.Property<decimal>("PorcentajeDegresivo")
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("porcentaje_degresivo_fiscal");

                            b1.Property<int>("VidaUtilAnios")
                                .HasColumnType("integer")
                                .HasColumnName("vida_util_fiscal");

                            b1.HasKey("InmovilizadoId");

                            b1.ToTable("inmovilizado", "contabilidad");

                            b1.WithOwner()
                                .HasForeignKey("InmovilizadoId");
                        });

                    b.OwnsMany("AlxorCore.Contabilidad.Dominio.AjusteFiscalAmortizacion", "AjustesFiscales", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AsientoId")
                                .HasColumnType("uuid")
                                .HasColumnName("asiento_id");

                            b1.Property<decimal>("DiferenciaTemporaria")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("diferencia_temporaria");

                            b1.Property<int>("Ejercicio")
                                .HasColumnType("integer")
                                .HasColumnName("ejercicio");

                            b1.Property<decimal>("TipoImpositivo")
                                .HasColumnType("numeric(6,4)")
                                .HasColumnName("tipo_impositivo");

                            b1.Property<Guid>("inmovilizado_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("inmovilizado_id");

                            b1.ToTable("ajuste_fiscal_amortizacion", "contabilidad");

                            b1.WithOwner()
                                .HasForeignKey("inmovilizado_id");
                        });

                    b.OwnsMany("AlxorCore.Contabilidad.Dominio.DotacionAmortizacion", "Dotaciones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AsientoId")
                                .HasColumnType("uuid")
                                .HasColumnName("asiento_id");

                            b1.Property<int>("Ejercicio")
                                .HasColumnType("integer")
                                .HasColumnName("ejercicio");

                            b1.Property<DateOnly>("Fecha")
                                .HasColumnType("date")
                                .HasColumnName("fecha");

                            b1.Property<decimal>("Importe")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("importe");

                            b1.Property<int>("Mes")
                                .HasColumnType("integer")
                                .HasColumnName("mes");

                            b1.Property<Guid>("inmovilizado_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("inmovilizado_id");

                            b1.ToTable("dotacion_amortizacion", "contabilidad");

                            b1.WithOwner()
                                .HasForeignKey("inmovilizado_id");
                        });

                    b.Navigation("AjustesFiscales");

                    b.Navigation("Contable")
                        .IsRequired();

                    b.Navigation("Dotaciones");

                    b.Navigation("Fiscal")
                        .IsRequired();
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.PartidaAnalitica", b =>
                {
                    b.HasOne("AlxorCore.Contabilidad.Dominio.PartidaAnalitica", null)
                        .WithMany()
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.Periodificacion", b =>
                {
                    b.OwnsMany("AlxorCore.Contabilidad.Dominio.CuotaPeriodificacion", "Cuotas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("AsientoId")
                                .HasColumnType("uuid")
                                .HasColumnName("asiento_id");

                            b1.Property<int>("Ejercicio")
                                .HasColumnType("integer")
                                .HasColumnName("ejercicio");

                            b1.Property<decimal>("Importe")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("importe");

                            b1.Property<int>("Mes")
                                .HasColumnType("integer")
                                .HasColumnName("mes");

                            b1.Property<Guid>("periodificacion_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("AsientoId")
                                .HasDatabaseName("ix_cuota_periodificacion_asiento");

                            b1.HasIndex("periodificacion_id", "Ejercicio", "Mes")
                                .IsUnique()
                                .HasDatabaseName("ux_cuota_periodificacion_mes");

                            b1.ToTable("cuota_periodificacion", "contabilidad");

                            b1.WithOwner()
                                .HasForeignKey("periodificacion_id");
                        });

                    b.Navigation("Cuotas");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.PresupuestoContable", b =>
                {
                    b.OwnsMany("AlxorCore.Contabilidad.Dominio.LineaPresupuesto", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("CentroId")
                                .HasColumnType("uuid")
                                .HasColumnName("centro_id");

                            b1.Property<string>("CuentaCodigo")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("cuenta_codigo");

                            b1.Property<decimal[]>("Importes")
                                .IsRequired()
                                .HasColumnType("numeric(14,2)[]")
                                .HasColumnName("importes");

                            b1.Property<Guid?>("PartidaId")
                                .HasColumnType("uuid")
                                .HasColumnName("partida_id");

                            b1.Property<Guid>("presupuesto_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("CentroId");

                            b1.HasIndex("PartidaId");

                            b1.HasIndex("presupuesto_id")
                                .HasDatabaseName("ix_linea_presupuesto_presupuesto");

                            b1.ToTable("linea_presupuesto", "contabilidad");

                            b1.HasOne("AlxorCore.Contabilidad.Dominio.CentroAnalitico", null)
                                .WithMany()
                                .HasForeignKey("CentroId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("AlxorCore.Contabilidad.Dominio.PartidaAnalitica", null)
                                .WithMany()
                                .HasForeignKey("PartidaId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner()
                                .HasForeignKey("presupuesto_id");
                        });

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("AlxorCore.Contabilidad.Dominio.ReglaAnalitica", b =>
                {
                    b.HasOne("AlxorCore.Contabilidad.Dominio.CentroAnalitico", null)
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlxorCore.Contabilidad.Dominio.ClaveReparto", null)
                        .WithMany()
                        .HasForeignKey("ClaveRepartoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlxorCore.Contabilidad.Dominio.PartidaAnalitica", null)
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
