<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Matchketing.Nucleo\Matchketing.Nucleo.csproj" />
    <ProjectReference Include="..\Matchketing.Identidad\Matchketing.Identidad.csproj" />
    <ProjectReference Include="..\Matchketing.Organizacion\Matchketing.Organizacion.csproj" />
    <ProjectReference Include="..\Matchketing.Contactos\Matchketing.Contactos.csproj" />
    <ProjectReference Include="..\Matchketing.Embudo\Matchketing.Embudo.csproj" />
  </ItemGroup>
</Project>
