// <auto-generated />
using System;
using AlxorCore.Proyectos.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Proyectos.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ProyectosDbContext))]
    partial class ProyectosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("proyectos")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Proyectos.Dominio.Proyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset?>("CerradoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cerrado_en");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ClienteNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cliente_nombre");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("presupuesto");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Ejercicio", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_proyecto_serie");

                    b.ToTable("proyecto", "proyectos");
                });

            modelBuilder.Entity("AlxorCore.Proyectos.Dominio.Proyecto", b =>
                {
                    b.OwnsMany("AlxorCore.Proyectos.Dominio.Imputacion", "Imputaciones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad");

                            b1.Property<decimal>("CosteUnitario")
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("coste_unitario");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("descripcion");

                            b1.Property<DateOnly>("Fecha")
                                .HasColumnType("date")
                                .HasColumnName("fecha");

                            b1.Property<decimal>("Importe")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("importe");

                            b1.Property<Guid?>("ReferenciaId")
                                .HasColumnType("uuid")
                                .HasColumnName("referencia_id");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("tipo");

                            b1.Property<Guid>("proyecto_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("proyecto_id");

                            b1.ToTable("imputacion", "proyectos");

                            b1.WithOwner()
                                .HasForeignKey("proyecto_id");
                        });

                    b.Navigation("Imputaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
