// <auto-generated />
using System;
using AlxorCore.Informes.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Informes.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(FiscalDbContext))]
    [Migration("20260928134639_SiiEnvio")]
    partial class SiiEnvio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fiscal")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Informes.Dominio.CertificadoSii", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CaducaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("caduca_en");

                    b.Property<string>("ClaveCifrada")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave_cifrada");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entorno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entorno");

                    b.Property<string>("Nif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<byte[]>("PfxCifrado")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pfx_cifrado");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("titular");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ux_certificado_empresa");

                    b.ToTable("certificado", "fiscal");
                });

            modelBuilder.Entity("AlxorCore.Informes.Dominio.EnvioSii", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConErrores")
                        .HasColumnType("integer")
                        .HasColumnName("con_errores");

                    b.Property<int>("Correctos")
                        .HasColumnType("integer")
                        .HasColumnName("correctos");

                    b.Property<string>("Csv")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("csv");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entorno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entorno");

                    b.Property<DateTimeOffset>("EnviadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_en");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<int>("Incorrectos")
                        .HasColumnType("integer")
                        .HasColumnName("incorrectos");

                    b.Property<string>("Libro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("libro");

                    b.Property<int>("Periodo")
                        .HasColumnType("integer")
                        .HasColumnName("periodo");

                    b.Property<string>("Peticion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("peticion");

                    b.Property<int>("Registros")
                        .HasColumnType("integer")
                        .HasColumnName("registros");

                    b.Property<string>("Respuesta")
                        .HasColumnType("text")
                        .HasColumnName("respuesta");

                    b.Property<string>("TipoComunicacion")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("tipo_comunicacion");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "EnviadoEn")
                        .HasDatabaseName("ix_envio_sii_empresa_fecha");

                    b.ToTable("envio_sii", "fiscal");
                });

            modelBuilder.Entity("AlxorCore.Informes.Dominio.RegistroSii", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Aceptado")
                        .HasColumnType("boolean")
                        .HasColumnName("aceptado");

                    b.Property<string>("CodigoError")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_error");

                    b.Property<string>("Csv")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("csv");

                    b.Property<string>("DescripcionError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion_error");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset?>("EnviadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaExpedicion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_expedicion");

                    b.Property<string>("Huella")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("huella");

                    b.Property<string>("Libro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("libro");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("numero");

                    b.Property<int>("Periodo")
                        .HasColumnType("integer")
                        .HasColumnName("periodo");

                    b.Property<Guid?>("UltimoEnvioId")
                        .HasColumnType("uuid")
                        .HasColumnName("ultimo_envio_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Libro", "DocumentoId")
                        .IsUnique()
                        .HasDatabaseName("ux_registro_sii_documento");

                    b.HasIndex("EmpresaId", "Libro", "Ejercicio", "Periodo")
                        .HasDatabaseName("ix_registro_sii_periodo");

                    b.ToTable("registro_sii", "fiscal");
                });
#pragma warning restore 612, 618
        }
    }
}
