// <auto-generated />
using System;
using AlxorCore.Agro.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Agro.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(AgroDbContext))]
    [Migration("20260927085208_AnulacionExpedicionPales")]
    partial class AnulacionExpedicionPales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("agro")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Agro.Dominio.Agricultor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AutofacturacionDesde")
                        .HasColumnType("date")
                        .HasColumnName("autofacturacion_desde");

                    b.Property<string>("CodigoImpuesto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_impuesto");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("MotivoBloqueo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo_bloqueo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PorcentajeRetencion")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("porcentaje_retencion");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("Regimen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("regimen");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ProveedorId")
                        .IsUnique()
                        .HasDatabaseName("ux_agricultor_proveedor");

                    b.ToTable("agricultor", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.ArticuloCampana", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampanaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campana_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("metodo");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.HasKey("Id");

                    b.HasIndex("CampanaId", "ProductoId")
                        .IsUnique()
                        .HasDatabaseName("ux_articulo_campana");

                    b.ToTable("articulo_campana", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.Campana", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_campana_codigo");

                    b.ToTable("campana", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("EsDestrio")
                        .HasColumnType("boolean")
                        .HasColumnName("es_destrio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_categoria_codigo");

                    b.ToTable("categoria", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.ClasificacionPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId")
                        .IsUnique()
                        .HasDatabaseName("ux_clasificacion_definitiva")
                        .HasFilter("estado = 'Definitiva'");

                    b.ToTable("clasificacion", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.ConceptoLiquidacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_concepto_liquidacion_codigo");

                    b.ToTable("concepto_liquidacion", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.ConfiguracionAgro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DigitoExtension")
                        .HasColumnType("integer")
                        .HasColumnName("digito_extension");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("PrefijoGs1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefijo_gs1");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ux_configuracion_empresa");

                    b.ToTable("configuracion", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.Genealogia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("destino_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<decimal>("KilosOrigen")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("kilos_origen");

                    b.Property<Guid>("OrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("origen_id");

                    b.Property<Guid>("ParteId")
                        .HasColumnType("uuid")
                        .HasColumnName("parte_id");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId")
                        .HasDatabaseName("ix_genealogia_destino");

                    b.HasIndex("ParteId")
                        .HasDatabaseName("ix_genealogia_parte");

                    b.HasIndex("OrigenId", "DestinoId")
                        .IsUnique()
                        .HasDatabaseName("ux_genealogia_origen_destino");

                    b.ToTable("genealogia", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.Liquidacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("APagar")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("a_pagar");

                    b.Property<Guid>("AgricultorId")
                        .HasColumnType("uuid")
                        .HasColumnName("agricultor_id");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_imponible");

                    b.Property<decimal>("Bruto")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("bruto");

                    b.Property<Guid>("CampanaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campana_id");

                    b.Property<string>("CodigoImpuesto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_impuesto");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<decimal>("CuotaImpuesto")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("cuota_impuesto");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<DateTimeOffset?>("EmitidaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emitida_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<Guid?>("GastoId")
                        .HasColumnType("uuid")
                        .HasColumnName("gasto_id");

                    b.Property<DateOnly>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<decimal>("Kilos")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("kilos");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo_anulacion");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<decimal>("PorcentajeImpuesto")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("porcentaje_impuesto");

                    b.Property<decimal>("PorcentajeRetencion")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("porcentaje_retencion");

                    b.Property<string>("Regimen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("regimen");

                    b.Property<decimal>("Retencion")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("retencion");

                    b.Property<decimal>("TotalDescuentos")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_descuentos");

                    b.Property<decimal>("TotalFactura")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_factura");

                    b.HasKey("Id");

                    b.HasIndex("AgricultorId")
                        .HasDatabaseName("ix_liquidacion_agricultor");

                    b.HasIndex("CampanaId")
                        .HasDatabaseName("ix_liquidacion_campana");

                    b.HasIndex("EmpresaId", "Ejercicio", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_liquidacion_numero");

                    b.ToTable("liquidacion", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.MovimientoEnvase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgricultorId")
                        .HasColumnType("uuid")
                        .HasColumnName("agricultor_id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("Concepto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("concepto");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("EnvaseProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("envase_producto_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<Guid?>("RecepcionId")
                        .HasColumnType("uuid")
                        .HasColumnName("recepcion_id");

                    b.HasKey("Id");

                    b.HasIndex("RecepcionId")
                        .HasDatabaseName("ix_movimiento_envase_recepcion");

                    b.HasIndex("AgricultorId", "EnvaseProductoId")
                        .HasDatabaseName("ix_movimiento_envase_agricultor");

                    b.ToTable("movimiento_envase", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.MovimientoPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Concepto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("concepto");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid?>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<string>("DocumentoTipo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("documento_tipo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Kilos")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("kilos");

                    b.Property<Guid?>("PaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("pale_id");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("PaleId")
                        .HasDatabaseName("ix_movimiento_partida_pale");

                    b.HasIndex("PartidaId", "PaleId")
                        .HasDatabaseName("ix_movimiento_partida_partida");

                    b.ToTable("movimiento_partida", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.Pale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaExpedicion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_expedicion");

                    b.Property<string>("ReferenciaExpedicion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("referencia_expedicion");

                    b.Property<string>("Sscc")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character(18)")
                        .HasColumnName("sscc")
                        .IsFixedLength();

                    b.Property<string>("Tipo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Sscc")
                        .IsUnique()
                        .HasDatabaseName("ux_pale_sscc");

                    b.ToTable("pale", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.Parcela", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<Guid>("AgricultorId")
                        .HasColumnType("uuid")
                        .HasColumnName("agricultor_id");

                    b.Property<Guid?>("CentroAnaliticoId")
                        .HasColumnType("uuid")
                        .HasColumnName("centro_analitico_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<string>("ReferenciaSigpac")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("referencia_sigpac");

                    b.Property<decimal?>("SuperficieHa")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("superficie_ha");

                    b.Property<string>("Variedad")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("variedad");

                    b.HasKey("Id");

                    b.HasIndex("AgricultorId")
                        .HasDatabaseName("ix_parcela_agricultor");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_parcela_codigo");

                    b.ToTable("parcela", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.ParteConfeccion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CampanaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campana_id");

                    b.Property<Guid?>("CentroAnaliticoId")
                        .HasColumnType("uuid")
                        .HasColumnName("centro_analitico_id");

                    b.Property<decimal>("CosteFruta")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("coste_fruta");

                    b.Property<decimal>("CosteIndirectos")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("coste_indirectos");

                    b.Property<decimal>("CosteManoObra")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("coste_mano_obra");

                    b.Property<decimal>("CosteMaquinaria")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("coste_maquinaria");

                    b.Property<decimal>("CosteMateriales")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("coste_materiales");

                    b.Property<decimal>("CosteTotal")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("coste_total");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<decimal>("PorcentajeIndirectos")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("porcentaje_indirectos");

                    b.Property<string>("Reparto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("reparto");

                    b.Property<DateTimeOffset?>("ValidadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validado_en");

                    b.HasKey("Id");

                    b.HasIndex("CampanaId")
                        .HasDatabaseName("ix_parte_confeccion_campana");

                    b.HasIndex("EmpresaId", "Fecha")
                        .HasDatabaseName("ix_parte_confeccion_fecha");

                    b.HasIndex("EmpresaId", "Ejercicio", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_parte_confeccion_numero");

                    b.ToTable("parte_confeccion", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgricultorId")
                        .HasColumnType("uuid")
                        .HasColumnName("agricultor_id");

                    b.Property<bool>("Anulada")
                        .HasColumnType("boolean")
                        .HasColumnName("anulada");

                    b.Property<string>("Calibre")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("calibre");

                    b.Property<Guid?>("CampanaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campana_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<decimal?>("CosteKg")
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("coste_kg");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("KilosIniciales")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("kilos_iniciales");

                    b.Property<Guid?>("LineaRecepcionId")
                        .HasColumnType("uuid")
                        .HasColumnName("linea_recepcion_id");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origen");

                    b.Property<Guid?>("ParcelaId")
                        .HasColumnType("uuid")
                        .HasColumnName("parcela_id");

                    b.Property<Guid?>("ParteConfeccionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parte_confeccion_id");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<Guid?>("RecepcionId")
                        .HasColumnType("uuid")
                        .HasColumnName("recepcion_id");

                    b.HasKey("Id");

                    b.HasIndex("AgricultorId")
                        .HasDatabaseName("ix_partida_agricultor");

                    b.HasIndex("CampanaId")
                        .HasDatabaseName("ix_partida_campana");

                    b.HasIndex("LineaRecepcionId")
                        .IsUnique()
                        .HasDatabaseName("ux_partida_linea_recepcion");

                    b.HasIndex("ParcelaId")
                        .HasDatabaseName("ix_partida_parcela");

                    b.HasIndex("ParteConfeccionId")
                        .HasDatabaseName("ix_partida_parte");

                    b.HasIndex("RecepcionId")
                        .HasDatabaseName("ix_partida_recepcion");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_partida_codigo");

                    b.ToTable("partida", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.PrecioLiquidacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampanaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campana_id");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<decimal>("PrecioKg")
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("precio_kg");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_precio_liquidacion_categoria");

                    b.HasIndex("CampanaId", "ProductoId", "Desde")
                        .HasDatabaseName("ix_precio_liquidacion_campana");

                    b.ToTable("precio_liquidacion", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.Recepcion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgricultorId")
                        .HasColumnType("uuid")
                        .HasColumnName("agricultor_id");

                    b.Property<DateTimeOffset?>("AnuladaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anulada_en");

                    b.Property<Guid>("CampanaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campana_id");

                    b.Property<string>("Conductor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("conductor");

                    b.Property<DateTimeOffset?>("ConfirmadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmada_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Matricula")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("matricula");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo_anulacion");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("AgricultorId")
                        .HasDatabaseName("ix_recepcion_agricultor");

                    b.HasIndex("CampanaId")
                        .HasDatabaseName("ix_recepcion_campana");

                    b.HasIndex("EmpresaId", "Fecha")
                        .HasDatabaseName("ix_recepcion_fecha");

                    b.HasIndex("EmpresaId", "Ejercicio", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_recepcion_numero");

                    b.ToTable("recepcion", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.TarifaCoste", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("categoria");

                    b.Property<decimal>("CosteUnitario")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("coste_unitario");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("recurso");

                    b.Property<string>("TipoHora")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_hora");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Recurso", "Categoria", "TipoHora", "Desde")
                        .HasDatabaseName("ix_tarifa_coste_busqueda");

                    b.ToTable("tarifa_coste", "agro");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.ClasificacionPartida", b =>
                {
                    b.OwnsMany("AlxorCore.Agro.Dominio.LineaClasificacion", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("CategoriaId")
                                .HasColumnType("uuid")
                                .HasColumnName("categoria_id");

                            b1.Property<decimal>("KgMuestra")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("kg_muestra");

                            b1.Property<Guid>("clasificacion_id")
                                .HasColumnType("uuid")
                                .HasColumnName("clasificacion_id");

                            b1.HasKey("Id");

                            b1.HasIndex("CategoriaId")
                                .HasDatabaseName("ix_linea_clasificacion_categoria");

                            b1.HasIndex("clasificacion_id", "CategoriaId")
                                .IsUnique()
                                .HasDatabaseName("ux_linea_clasificacion_categoria");

                            b1.ToTable("linea_clasificacion", "agro");

                            b1.WithOwner()
                                .HasForeignKey("clasificacion_id");
                        });

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.Liquidacion", b =>
                {
                    b.OwnsMany("AlxorCore.Agro.Dominio.DescuentoLiquidacion", "Descuentos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Base")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("base");

                            b1.Property<Guid>("ConceptoId")
                                .HasColumnType("uuid")
                                .HasColumnName("concepto_id");

                            b1.Property<decimal>("Importe")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("importe");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("nombre");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("tipo");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("valor");

                            b1.Property<Guid>("liquidacion_id")
                                .HasColumnType("uuid")
                                .HasColumnName("liquidacion_id");

                            b1.HasKey("Id");

                            b1.HasIndex("ConceptoId")
                                .HasDatabaseName("ix_descuento_liquidacion_concepto");

                            b1.HasIndex("liquidacion_id")
                                .HasDatabaseName("ix_descuento_liquidacion_liquidacion");

                            b1.ToTable("descuento_liquidacion", "agro");

                            b1.WithOwner()
                                .HasForeignKey("liquidacion_id");
                        });

                    b.OwnsMany("AlxorCore.Agro.Dominio.LineaLiquidacion", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("CategoriaId")
                                .HasColumnType("uuid")
                                .HasColumnName("categoria_id");

                            b1.Property<DateOnly>("FechaRecepcion")
                                .HasColumnType("date")
                                .HasColumnName("fecha_recepcion");

                            b1.Property<decimal>("Importe")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("importe");

                            b1.Property<decimal>("Kilos")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("kilos");

                            b1.Property<Guid>("LineaRecepcionId")
                                .HasColumnType("uuid")
                                .HasColumnName("linea_recepcion_id");

                            b1.Property<Guid>("PartidaId")
                                .HasColumnType("uuid")
                                .HasColumnName("partida_id");

                            b1.Property<Guid>("PrecioId")
                                .HasColumnType("uuid")
                                .HasColumnName("precio_id");

                            b1.Property<decimal>("PrecioKg")
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("precio_kg");

                            b1.Property<Guid>("RecepcionId")
                                .HasColumnType("uuid")
                                .HasColumnName("recepcion_id");

                            b1.Property<Guid>("liquidacion_id")
                                .HasColumnType("uuid")
                                .HasColumnName("liquidacion_id");

                            b1.HasKey("Id");

                            b1.HasIndex("CategoriaId")
                                .HasDatabaseName("ix_linea_liquidacion_categoria");

                            b1.HasIndex("LineaRecepcionId")
                                .HasDatabaseName("ix_linea_liquidacion_linea_recepcion");

                            b1.HasIndex("PartidaId")
                                .HasDatabaseName("ix_linea_liquidacion_partida");

                            b1.HasIndex("PrecioId")
                                .HasDatabaseName("ix_linea_liquidacion_precio");

                            b1.HasIndex("RecepcionId")
                                .HasDatabaseName("ix_linea_liquidacion_recepcion");

                            b1.HasIndex("liquidacion_id")
                                .HasDatabaseName("ix_linea_liquidacion_liquidacion");

                            b1.ToTable("linea_liquidacion", "agro");

                            b1.WithOwner()
                                .HasForeignKey("liquidacion_id");
                        });

                    b.Navigation("Descuentos");

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.ParteConfeccion", b =>
                {
                    b.OwnsMany("AlxorCore.Agro.Dominio.ConsumoParte", "Consumos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Coste")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("coste");

                            b1.Property<decimal>("CosteKg")
                                .HasColumnType("numeric(14,6)")
                                .HasColumnName("coste_kg");

                            b1.Property<decimal>("Kilos")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("kilos");

                            b1.Property<Guid?>("PaleId")
                                .HasColumnType("uuid")
                                .HasColumnName("pale_id");

                            b1.Property<Guid>("PartidaId")
                                .HasColumnType("uuid")
                                .HasColumnName("partida_id");

                            b1.Property<Guid>("parte_id")
                                .HasColumnType("uuid")
                                .HasColumnName("parte_id");

                            b1.HasKey("Id");

                            b1.HasIndex("PaleId")
                                .HasDatabaseName("ix_consumo_parte_pale");

                            b1.HasIndex("PartidaId")
                                .HasDatabaseName("ix_consumo_parte_partida");

                            b1.HasIndex("parte_id")
                                .HasDatabaseName("ix_consumo_parte_parte");

                            b1.ToTable("consumo_parte", "agro");

                            b1.WithOwner()
                                .HasForeignKey("parte_id");
                        });

                    b.OwnsMany("AlxorCore.Agro.Dominio.ManoObraParte", "ManoObra", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Categoria")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("categoria");

                            b1.Property<decimal>("Coste")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("coste");

                            b1.Property<decimal>("CosteUnitario")
                                .HasColumnType("numeric(12,4)")
                                .HasColumnName("coste_unitario");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("descripcion");

                            b1.Property<decimal>("Horas")
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("horas");

                            b1.Property<decimal?>("Piezas")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("piezas");

                            b1.Property<Guid?>("TarifaId")
                                .HasColumnType("uuid")
                                .HasColumnName("tarifa_id");

                            b1.Property<string>("TipoHora")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("tipo_hora");

                            b1.Property<Guid>("parte_id")
                                .HasColumnType("uuid")
                                .HasColumnName("parte_id");

                            b1.HasKey("Id");

                            b1.HasIndex("TarifaId")
                                .HasDatabaseName("ix_mano_obra_parte_tarifa");

                            b1.HasIndex("parte_id")
                                .HasDatabaseName("ix_mano_obra_parte_parte");

                            b1.ToTable("mano_obra_parte", "agro");

                            b1.WithOwner()
                                .HasForeignKey("parte_id");
                        });

                    b.OwnsMany("AlxorCore.Agro.Dominio.MaquinaParte", "Maquinas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Categoria")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("categoria");

                            b1.Property<decimal>("Coste")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("coste");

                            b1.Property<decimal>("CosteUnitario")
                                .HasColumnType("numeric(12,4)")
                                .HasColumnName("coste_unitario");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("descripcion");

                            b1.Property<decimal>("Horas")
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("horas");

                            b1.Property<Guid?>("TarifaId")
                                .HasColumnType("uuid")
                                .HasColumnName("tarifa_id");

                            b1.Property<Guid>("parte_id")
                                .HasColumnType("uuid")
                                .HasColumnName("parte_id");

                            b1.HasKey("Id");

                            b1.HasIndex("TarifaId")
                                .HasDatabaseName("ix_maquina_parte_tarifa");

                            b1.HasIndex("parte_id")
                                .HasDatabaseName("ix_maquina_parte_parte");

                            b1.ToTable("maquina_parte", "agro");

                            b1.WithOwner()
                                .HasForeignKey("parte_id");
                        });

                    b.OwnsMany("AlxorCore.Agro.Dominio.MaterialParte", "Materiales", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("cantidad");

                            b1.Property<decimal>("Coste")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("coste");

                            b1.Property<decimal>("CosteUnitario")
                                .HasColumnType("numeric(12,4)")
                                .HasColumnName("coste_unitario");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("nombre");

                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("producto_id");

                            b1.Property<Guid>("parte_id")
                                .HasColumnType("uuid")
                                .HasColumnName("parte_id");

                            b1.HasKey("Id");

                            b1.HasIndex("parte_id")
                                .HasDatabaseName("ix_material_parte_parte");

                            b1.ToTable("material_parte", "agro");

                            b1.WithOwner()
                                .HasForeignKey("parte_id");
                        });

                    b.OwnsMany("AlxorCore.Agro.Dominio.SalidaParte", "Salidas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Calibre")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("calibre");

                            b1.Property<Guid?>("CategoriaId")
                                .HasColumnType("uuid")
                                .HasColumnName("categoria_id");

                            b1.Property<decimal>("Coste")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("coste");

                            b1.Property<decimal>("Factor")
                                .HasColumnType("numeric(8,4)")
                                .HasColumnName("factor");

                            b1.Property<decimal>("Kilos")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("kilos");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("nombre");

                            b1.Property<int>("NumeroLinea")
                                .HasColumnType("integer")
                                .HasColumnName("numero_linea");

                            b1.Property<Guid?>("PaleId")
                                .HasColumnType("uuid")
                                .HasColumnName("pale_id");

                            b1.Property<Guid?>("PartidaId")
                                .HasColumnType("uuid")
                                .HasColumnName("partida_id");

                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("producto_id");

                            b1.Property<Guid>("parte_id")
                                .HasColumnType("uuid")
                                .HasColumnName("parte_id");

                            b1.HasKey("Id");

                            b1.HasIndex("CategoriaId")
                                .HasDatabaseName("ix_salida_parte_categoria");

                            b1.HasIndex("PaleId")
                                .HasDatabaseName("ix_salida_parte_pale");

                            b1.HasIndex("PartidaId")
                                .HasDatabaseName("ix_salida_parte_partida");

                            b1.HasIndex("parte_id", "NumeroLinea")
                                .IsUnique()
                                .HasDatabaseName("ux_salida_parte_numero");

                            b1.ToTable("salida_parte", "agro");

                            b1.WithOwner()
                                .HasForeignKey("parte_id");
                        });

                    b.Navigation("Consumos");

                    b.Navigation("ManoObra");

                    b.Navigation("Maquinas");

                    b.Navigation("Materiales");

                    b.Navigation("Salidas");
                });

            modelBuilder.Entity("AlxorCore.Agro.Dominio.Recepcion", b =>
                {
                    b.OwnsMany("AlxorCore.Agro.Dominio.LineaRecepcion", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Calibre")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("calibre");

                            b1.Property<Guid?>("EnvaseProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("envase_producto_id");

                            b1.Property<int?>("Envases")
                                .HasColumnType("integer")
                                .HasColumnName("envases");

                            b1.Property<DateOnly?>("FechaRecoleccion")
                                .HasColumnType("date")
                                .HasColumnName("fecha_recoleccion");

                            b1.Property<decimal?>("NetoKg")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("neto_kg");

                            b1.Property<int>("NumeroLinea")
                                .HasColumnType("integer")
                                .HasColumnName("numero_linea");

                            b1.Property<Guid?>("ParcelaId")
                                .HasColumnType("uuid")
                                .HasColumnName("parcela_id");

                            b1.Property<Guid?>("PartidaId")
                                .HasColumnType("uuid")
                                .HasColumnName("partida_id");

                            b1.Property<decimal?>("PrecioEstimadoKg")
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("precio_estimado_kg");

                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("producto_id");

                            b1.Property<string>("ProductoNombre")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("producto_nombre");

                            b1.Property<Guid>("recepcion_id")
                                .HasColumnType("uuid")
                                .HasColumnName("recepcion_id");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelaId")
                                .HasDatabaseName("ix_linea_recepcion_parcela");

                            b1.HasIndex("PartidaId")
                                .HasDatabaseName("ix_linea_recepcion_partida");

                            b1.HasIndex("recepcion_id", "NumeroLinea")
                                .IsUnique()
                                .HasDatabaseName("ux_linea_recepcion_numero");

                            b1.ToTable("linea_recepcion", "agro");

                            b1.WithOwner()
                                .HasForeignKey("recepcion_id");
                        });

                    b.OwnsMany("AlxorCore.Agro.Dominio.Pesada", "Pesadas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Bascula")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("bascula");

                            b1.Property<decimal>("BrutoKg")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("bruto_kg");

                            b1.Property<int>("Envases")
                                .HasColumnType("integer")
                                .HasColumnName("envases");

                            b1.Property<Guid>("LineaId")
                                .HasColumnType("uuid")
                                .HasColumnName("linea_id");

                            b1.Property<int>("Secuencia")
                                .HasColumnType("integer")
                                .HasColumnName("secuencia");

                            b1.Property<decimal>("TaraKg")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("tara_kg");

                            b1.Property<Guid>("recepcion_id")
                                .HasColumnType("uuid")
                                .HasColumnName("recepcion_id");

                            b1.HasKey("Id");

                            b1.HasIndex("recepcion_id")
                                .HasDatabaseName("ix_pesada_recepcion");

                            b1.HasIndex("LineaId", "Secuencia")
                                .IsUnique()
                                .HasDatabaseName("ux_pesada_secuencia");

                            b1.ToTable("pesada", "agro");

                            b1.WithOwner()
                                .HasForeignKey("recepcion_id");
                        });

                    b.Navigation("Lineas");

                    b.Navigation("Pesadas");
                });
#pragma warning restore 612, 618
        }
    }
}
