// <auto-generated />
using System;
using AlxorCore.Aprobaciones.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Aprobaciones.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(AprobacionesDbContext))]
    [Migration("20260823052834_MigracionInicialAprobaciones")]
    partial class MigracionInicialAprobaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("aprobaciones")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Aprobaciones.Dominio.ReglaAprobacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo_documento");

                    b.Property<decimal>("UmbralImporte")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("umbral_importe");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "TipoDocumento")
                        .IsUnique()
                        .HasDatabaseName("ux_regla_aprobacion_empresa_tipo");

                    b.ToTable("regla_aprobacion", "aprobaciones");
                });

            modelBuilder.Entity("AlxorCore.Aprobaciones.Dominio.SolicitudAprobacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AprobadorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("aprobador_usuario_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("importe");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("referencia");

                    b.Property<DateTimeOffset?>("ResueltaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resuelta_en");

                    b.Property<Guid>("SolicitanteUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitante_usuario_id");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Estado", "CreadoEn")
                        .HasDatabaseName("ix_solicitud_aprobacion_empresa_estado");

                    b.ToTable("solicitud_aprobacion", "aprobaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
