<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>AlxorCore.Compras</RootNamespace>
    <AssemblyName>AlxorCore.Compras</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AlxorCore.Nucleo\AlxorCore.Nucleo.csproj" />
    <ProjectReference Include="..\AlxorCore.Organizacion\AlxorCore.Organizacion.csproj" />
    <ProjectReference Include="..\AlxorCore.Terceros\AlxorCore.Terceros.csproj" />
    <ProjectReference Include="..\AlxorCore.Recepcion\AlxorCore.Recepcion.csproj" />
  </ItemGroup>
</Project>
