// <auto-generated />
using System;
using AlxorCore.Extensiones.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Extensiones.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ExtensionesDbContext))]
    [Migration("20261005184215_EtiquetasCliente")]
    partial class EtiquetasCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("extensiones")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.Adjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entidad");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<string>("Huella")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("huella");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("SubidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subido_en");

                    b.Property<string>("SubidoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subido_por");

                    b.Property<Guid?>("SubidoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("subido_por_id");

                    b.Property<long>("Tamano")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_mime");

                    b.HasKey("Id");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("ix_adjunto_entidad");

                    b.ToTable("adjunto", "extensiones");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detalle");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entidad");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<string>("PermisoDestino")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("permiso_destino");

                    b.Property<Guid>("ReglaId")
                        .HasColumnType("uuid")
                        .HasColumnName("regla_id");

                    b.Property<DateTimeOffset?>("ResueltaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resuelta_en");

                    b.Property<string>("ResueltaPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resuelta_por");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "CreadaEn")
                        .HasDatabaseName("ix_alerta_empresa_fecha");

                    b.HasIndex("ReglaId", "Clave")
                        .IsUnique()
                        .HasDatabaseName("ux_alerta_viva_clave")
                        .HasFilter("resuelta_en IS NULL");

                    b.ToTable("alerta", "extensiones");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.ContenidoAdjunto", b =>
                {
                    b.Property<Guid>("AdjuntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("adjunto_id");

                    b.Property<byte[]>("Datos")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("datos");

                    b.HasKey("AdjuntoId");

                    b.ToTable("adjunto_contenido", "extensiones");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.DefinicionCampo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Ayuda")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("ayuda");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entidad");

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("etiqueta");

                    b.Property<bool>("Obligatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("obligatorio");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<string>("ValorPorDefecto")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("valor_por_defecto");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Entidad", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_definicion_campo_codigo");

                    b.ToTable("definicion_campo", "extensiones");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.LecturaAlerta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlertaId")
                        .HasColumnType("uuid")
                        .HasColumnName("alerta_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("LeidaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leida_en");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_lectura_alerta_usuario");

                    b.HasIndex("AlertaId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ux_lectura_alerta_usuario");

                    b.ToTable("lectura_alerta", "extensiones");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.PlantillaEtiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Campos")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("campos");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("formato");

                    b.Property<string>("Marca")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("marca");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("TextoLibre")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("texto_libre");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_plantilla_etiqueta_cliente");

                    b.ToTable("plantilla_etiqueta", "extensiones");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.ReferenciaCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Gtin")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("gtin");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_referencia_cliente_producto");

                    b.HasIndex("EmpresaId", "ClienteId", "ProductoId")
                        .IsUnique()
                        .HasDatabaseName("ux_referencia_cliente_producto");

                    b.ToTable("referencia_cliente", "extensiones");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.ReglaAlerta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<Guid?>("CampoId")
                        .HasColumnType("uuid")
                        .HasColumnName("campo_id");

                    b.Property<int?>("Dias")
                        .HasColumnType("integer")
                        .HasColumnName("dias");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Evento")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("evento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("PermisoDestino")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("permiso_destino");

                    b.Property<decimal?>("Porcentaje")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("porcentaje");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset?>("UltimaEvaluacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_evaluacion");

                    b.HasKey("Id");

                    b.HasIndex("CampoId")
                        .HasDatabaseName("ix_regla_alerta_campo");

                    b.ToTable("regla_alerta", "extensiones");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.ValorCampo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<Guid>("DefinicionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definicion_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entidad");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("DefinicionId", "EntidadId")
                        .IsUnique()
                        .HasDatabaseName("ux_valor_campo_registro");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("ix_valor_campo_entidad");

                    b.ToTable("valor_campo", "extensiones");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.Alerta", b =>
                {
                    b.HasOne("AlxorCore.Extensiones.Dominio.ReglaAlerta", null)
                        .WithMany()
                        .HasForeignKey("ReglaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerta_regla");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.ContenidoAdjunto", b =>
                {
                    b.HasOne("AlxorCore.Extensiones.Dominio.Adjunto", null)
                        .WithOne("Contenido")
                        .HasForeignKey("AlxorCore.Extensiones.Dominio.ContenidoAdjunto", "AdjuntoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_adjunto_contenido_adjunto");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.DefinicionCampo", b =>
                {
                    b.OwnsMany("AlxorCore.Extensiones.Dominio.OpcionCampo", "Opciones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Orden")
                                .HasColumnType("integer")
                                .HasColumnName("orden");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("valor");

                            b1.Property<Guid>("definicion_campo_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("definicion_campo_id", "Orden")
                                .HasDatabaseName("ix_opcion_campo_orden");

                            b1.ToTable("opcion_campo", "extensiones");

                            b1.WithOwner()
                                .HasForeignKey("definicion_campo_id");
                        });

                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.LecturaAlerta", b =>
                {
                    b.HasOne("AlxorCore.Extensiones.Dominio.Alerta", null)
                        .WithMany()
                        .HasForeignKey("AlertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lectura_alerta_alerta");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.ReglaAlerta", b =>
                {
                    b.HasOne("AlxorCore.Extensiones.Dominio.DefinicionCampo", null)
                        .WithMany()
                        .HasForeignKey("CampoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_regla_alerta_campo");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.ValorCampo", b =>
                {
                    b.HasOne("AlxorCore.Extensiones.Dominio.DefinicionCampo", null)
                        .WithMany()
                        .HasForeignKey("DefinicionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_valor_campo_definicion");
                });

            modelBuilder.Entity("AlxorCore.Extensiones.Dominio.Adjunto", b =>
                {
                    b.Navigation("Contenido")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
