// <auto-generated />
using System;
using AlxorCore.Personal.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Personal.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(PersonalDbContext))]
    [Migration("20260822083110_MigracionInicialPersonal")]
    partial class MigracionInicialPersonal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("personal")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Personal.Dominio.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Puesto")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("puesto");

                    b.Property<decimal>("TarifaHora")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tarifa_hora");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Activo")
                        .HasDatabaseName("ix_persona_empresa");

                    b.ToTable("persona", "personal");
                });
#pragma warning restore 612, 618
        }
    }
}
