<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>AlxorCore.Contabilidad</RootNamespace>
    <AssemblyName>AlxorCore.Contabilidad</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AlxorCore.Nucleo\AlxorCore.Nucleo.csproj" />
  </ItemGroup>
</Project>
