// <auto-generated />
using System;
using AlxorCore.Bodega.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Bodega.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(BodegaDbContext))]
    [Migration("20261005104525_InicialBodega")]
    partial class InicialBodega
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bodega")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Bodega.Dominio.Deposito", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Calificacion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("calificacion");

                    b.Property<decimal>("CapacidadLitros")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("capacidad_litros");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<decimal>("Litros")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("litros");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("Producto")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("producto");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UltimaOperacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ultima_operacion_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_deposito_codigo");

                    b.ToTable("deposito", "bodega");
                });

            modelBuilder.Entity("AlxorCore.Bodega.Dominio.EntradaUva", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Anada")
                        .HasColumnType("integer")
                        .HasColumnName("anada");

                    b.Property<bool>("Anulada")
                        .HasColumnType("boolean")
                        .HasColumnName("anulada");

                    b.Property<string>("Calificacion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("calificacion");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("GradoBaume")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("grado_baume");

                    b.Property<decimal>("Kilos")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("kilos");

                    b.Property<Guid?>("LiquidacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("liquidacion_id");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo_anulacion");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<Guid?>("OperacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("operacion_id");

                    b.Property<string>("Parcela")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("parcela");

                    b.Property<string>("Variedad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("variedad");

                    b.Property<Guid>("ViticultorId")
                        .HasColumnType("uuid")
                        .HasColumnName("viticultor_id");

                    b.Property<string>("ViticultorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("viticultor_nombre");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacionId")
                        .HasDatabaseName("ix_entrada_uva_liquidacion");

                    b.HasIndex("OperacionId")
                        .HasDatabaseName("ix_entrada_uva_operacion");

                    b.HasIndex("ViticultorId")
                        .HasDatabaseName("ix_entrada_uva_proveedor");

                    b.HasIndex("EmpresaId", "Ejercicio", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_entrada_uva_numero");

                    b.HasIndex("EmpresaId", "ViticultorId", "Fecha")
                        .HasDatabaseName("ix_entrada_uva_viticultor");

                    b.ToTable("entrada_uva", "bodega");
                });

            modelBuilder.Entity("AlxorCore.Bodega.Dominio.LiquidacionUva", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_imponible");

                    b.Property<string>("CodigoImpuesto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_impuesto");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<Guid?>("GastoId")
                        .HasColumnType("uuid")
                        .HasColumnName("gasto_id");

                    b.Property<DateOnly>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<decimal>("Kilos")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("kilos");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo_anulacion");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<decimal>("PorcentajeRetencion")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_retencion");

                    b.Property<decimal>("TotalFactura")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_factura");

                    b.Property<Guid>("ViticultorId")
                        .HasColumnType("uuid")
                        .HasColumnName("viticultor_id");

                    b.Property<string>("ViticultorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("viticultor_nombre");

                    b.HasKey("Id");

                    b.HasIndex("ViticultorId")
                        .HasDatabaseName("ix_liquidacion_uva_proveedor");

                    b.HasIndex("EmpresaId", "Ejercicio", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_liquidacion_uva_numero");

                    b.ToTable("liquidacion_uva", "bodega");
                });

            modelBuilder.Entity("AlxorCore.Bodega.Dominio.OperacionBodega", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AlbaranId")
                        .HasColumnType("uuid")
                        .HasColumnName("albaran_id");

                    b.Property<string>("AlbaranNumero")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("albaran_numero");

                    b.Property<bool>("Anulada")
                        .HasColumnType("boolean")
                        .HasColumnName("anulada");

                    b.Property<int?>("Botellas")
                        .HasColumnType("integer")
                        .HasColumnName("botellas");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal?>("FormatoLitros")
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("formato_litros");

                    b.Property<decimal?>("KilosUva")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("kilos_uva");

                    b.Property<string>("Lote")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("lote");

                    b.Property<decimal>("MermaLitros")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("merma_litros");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo_anulacion");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_operacion_bodega_cliente");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_operacion_bodega_producto");

                    b.HasIndex("EmpresaId", "Fecha")
                        .HasDatabaseName("ix_operacion_bodega_fecha");

                    b.HasIndex("EmpresaId", "Ejercicio", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_operacion_bodega_numero");

                    b.ToTable("operacion", "bodega");
                });

            modelBuilder.Entity("AlxorCore.Bodega.Dominio.PrecioUva", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Anada")
                        .HasColumnType("integer")
                        .HasColumnName("anada");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<decimal>("GradoReferencia")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("grado_referencia");

                    b.Property<decimal>("PorcentajePorGrado")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("porcentaje_por_grado");

                    b.Property<decimal>("PrecioKg")
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("precio_kg");

                    b.Property<string>("Variedad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("variedad");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Anada", "Variedad")
                        .IsUnique()
                        .HasDatabaseName("ux_precio_uva");

                    b.ToTable("precio_uva", "bodega");
                });

            modelBuilder.Entity("AlxorCore.Bodega.Dominio.Deposito", b =>
                {
                    b.OwnsMany("AlxorCore.Bodega.Dominio.ComponenteDeposito", "Composicion", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Anada")
                                .HasColumnType("integer")
                                .HasColumnName("anada");

                            b1.Property<decimal>("Litros")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("litros");

                            b1.Property<string>("Variedad")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("variedad");

                            b1.Property<Guid>("deposito_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("deposito_id", "Variedad", "Anada")
                                .IsUnique()
                                .HasDatabaseName("ux_componente_deposito");

                            b1.ToTable("componente_deposito", "bodega");

                            b1.WithOwner()
                                .HasForeignKey("deposito_id");
                        });

                    b.Navigation("Composicion");
                });

            modelBuilder.Entity("AlxorCore.Bodega.Dominio.LiquidacionUva", b =>
                {
                    b.OwnsMany("AlxorCore.Bodega.Dominio.LineaLiquidacionUva", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Entrada")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("entrada");

                            b1.Property<Guid>("EntradaUvaId")
                                .HasColumnType("uuid")
                                .HasColumnName("entrada_uva_id");

                            b1.Property<decimal>("GradoBaume")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("grado_baume");

                            b1.Property<decimal>("Importe")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("importe");

                            b1.Property<decimal>("Kilos")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("kilos");

                            b1.Property<decimal>("PrecioKg")
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("precio_kg");

                            b1.Property<string>("Variedad")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("variedad");

                            b1.Property<Guid>("liquidacion_uva_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("EntradaUvaId")
                                .HasDatabaseName("ix_linea_liquidacion_uva_entrada");

                            b1.HasIndex("liquidacion_uva_id");

                            b1.ToTable("linea_liquidacion_uva", "bodega");

                            b1.WithOwner()
                                .HasForeignKey("liquidacion_uva_id");
                        });

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("AlxorCore.Bodega.Dominio.OperacionBodega", b =>
                {
                    b.OwnsMany("AlxorCore.Bodega.Dominio.LineaOperacionBodega", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Calificacion")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("calificacion");

                            b1.Property<string>("Clase")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("clase");

                            b1.Property<string>("DepositoCodigo")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("deposito_codigo");

                            b1.Property<Guid>("DepositoId")
                                .HasColumnType("uuid")
                                .HasColumnName("deposito_id");

                            b1.Property<string>("EstadoAnterior")
                                .HasColumnType("jsonb")
                                .HasColumnName("estado_anterior");

                            b1.Property<decimal>("Litros")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("litros");

                            b1.Property<int>("Orden")
                                .HasColumnType("integer")
                                .HasColumnName("orden");

                            b1.Property<string>("Producto")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("producto");

                            b1.Property<Guid>("operacion_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("DepositoId")
                                .HasDatabaseName("ix_linea_operacion_deposito");

                            b1.HasIndex("operacion_id", "Orden")
                                .IsUnique()
                                .HasDatabaseName("ux_linea_operacion_orden");

                            b1.ToTable("linea_operacion", "bodega");

                            b1.HasOne("AlxorCore.Bodega.Dominio.Deposito", null)
                                .WithMany()
                                .HasForeignKey("DepositoId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("fk_linea_operacion_deposito");

                            b1.WithOwner()
                                .HasForeignKey("operacion_id");
                        });

                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
