// <auto-generated />
using System;
using Matchketing.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matchketing.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoMatchketing))]
    [Migration("20260816170418_Tareas")]
    partial class Tareas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("publico")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matchketing.Contactos.Dominio.Actividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<Guid>("ContactoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contacto_id");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("cuerpo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("OcurridaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrida_en");

                    b.Property<int?>("Resultado")
                        .HasColumnType("integer")
                        .HasColumnName("resultado");

                    b.Property<int>("Sentido")
                        .HasColumnType("integer")
                        .HasColumnName("sentido");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.HasIndex("EmpresaId", "ContactoId", "OcurridaEn")
                        .HasDatabaseName("ix_actividad_empresa_contacto_fecha");

                    b.ToTable("actividad", "contactos");
                });

            modelBuilder.Entity("Matchketing.Contactos.Dominio.Contacto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid?>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<Guid?>("FusionadoEnId")
                        .HasColumnType("uuid")
                        .HasColumnName("fusionado_en_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nombre");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("origen");

                    b.Property<Guid?>("PropietarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("propietario_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.HasIndex("EmpresaId", "Email")
                        .HasDatabaseName("ix_contacto_empresa_email");

                    b.HasIndex("EmpresaId", "Telefono")
                        .HasDatabaseName("ix_contacto_empresa_telefono");

                    b.ToTable("contacto", "contactos");
                });

            modelBuilder.Entity("Matchketing.Contactos.Dominio.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nombre");

                    b.Property<string>("Provincia")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("provincia");

                    b.Property<string>("Sector")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("sector");

                    b.Property<int?>("Tamano")
                        .HasColumnType("integer")
                        .HasColumnName("tamano");

                    b.Property<string>("Web")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("web");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nombre")
                        .HasDatabaseName("ix_cuenta_empresa_nombre");

                    b.ToTable("cuenta", "contactos");
                });

            modelBuilder.Entity("Matchketing.Embudo.Dominio.Embudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<bool>("PorDefecto")
                        .HasColumnType("boolean")
                        .HasColumnName("por_defecto");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "PorDefecto")
                        .HasDatabaseName("ix_embudo_empresa_defecto");

                    b.ToTable("embudo", "embudo");
                });

            modelBuilder.Entity("Matchketing.Embudo.Dominio.Etapa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DiasAviso")
                        .HasColumnType("integer")
                        .HasColumnName("dias_aviso");

                    b.Property<Guid>("EmbudoId")
                        .HasColumnType("uuid")
                        .HasColumnName("embudo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("Probabilidad")
                        .HasColumnType("integer")
                        .HasColumnName("probabilidad");

                    b.HasKey("Id");

                    b.HasIndex("EmbudoId", "Orden")
                        .HasDatabaseName("ix_etapa_embudo_orden");

                    b.ToTable("etapa", "embudo");
                });

            modelBuilder.Entity("Matchketing.Embudo.Dominio.Oportunidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset?>("CerradaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cerrada_en");

                    b.Property<Guid>("ContactoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contacto_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid?>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<string>("DetalleMotivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detalle_motivo");

                    b.Property<Guid>("EmbudoId")
                        .HasColumnType("uuid")
                        .HasColumnName("embudo_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("EntroEnEtapaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entro_en_etapa_en");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etapa_id");

                    b.Property<decimal>("Importe")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("importe");

                    b.Property<int?>("Motivo")
                        .HasColumnType("integer")
                        .HasColumnName("motivo");

                    b.Property<DateOnly?>("PrevistaCierre")
                        .HasColumnType("date")
                        .HasColumnName("prevista_cierre");

                    b.Property<Guid?>("PropietarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("propietario_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("EmpresaId", "CerradaEn")
                        .HasDatabaseName("ix_oportunidad_empresa_cerrada");

                    b.HasIndex("EmpresaId", "ContactoId")
                        .HasDatabaseName("ix_oportunidad_empresa_contacto");

                    b.HasIndex("EmpresaId", "EtapaId")
                        .HasDatabaseName("ix_oportunidad_empresa_etapa");

                    b.ToTable("oportunidad", "embudo");
                });

            modelBuilder.Entity("Matchketing.Identidad.Dominio.Membresia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ix_membresia_usuario_empresa");

                    b.ToTable("membresia", "identidad");
                });

            modelBuilder.Entity("Matchketing.Identidad.Dominio.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verificado");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("hash_contrasena");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset?>("UltimoAccesoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso_en");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_email");

                    b.ToTable("usuario", "identidad");
                });

            modelBuilder.Entity("Matchketing.Organizacion.Dominio.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("HorasRebote")
                        .HasColumnType("integer")
                        .HasColumnName("horas_rebote");

                    b.Property<string>("Nif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PesoEncaje")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("peso_encaje");

                    b.Property<string>("Provincia")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("provincia");

                    b.HasKey("Id");

                    b.ToTable("empresa", "organizacion");
                });

            modelBuilder.Entity("Matchketing.Tareas.Dominio.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset?>("CerradaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cerrada_en");

                    b.Property<Guid?>("ContactoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contacto_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<Guid?>("OportunidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("oportunidad_id");

                    b.Property<int>("Origen")
                        .HasColumnType("integer")
                        .HasColumnName("origen");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsable_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("titulo");

                    b.Property<int>("VecesAplazada")
                        .HasColumnType("integer")
                        .HasColumnName("veces_aplazada");

                    b.Property<DateOnly>("VenceEl")
                        .HasColumnType("date")
                        .HasColumnName("vence_el");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ContactoId")
                        .HasDatabaseName("ix_tarea_empresa_contacto");

                    b.HasIndex("EmpresaId", "Estado", "VenceEl")
                        .HasDatabaseName("ix_tarea_empresa_estado_vence");

                    b.ToTable("tarea", "tareas");
                });

            modelBuilder.Entity("Matchketing.Contactos.Dominio.Actividad", b =>
                {
                    b.HasOne("Matchketing.Contactos.Dominio.Contacto", null)
                        .WithMany()
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Matchketing.Contactos.Dominio.Contacto", b =>
                {
                    b.HasOne("Matchketing.Contactos.Dominio.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Matchketing.Embudo.Dominio.Etapa", b =>
                {
                    b.HasOne("Matchketing.Embudo.Dominio.Embudo", null)
                        .WithMany("Etapas")
                        .HasForeignKey("EmbudoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Matchketing.Embudo.Dominio.Oportunidad", b =>
                {
                    b.HasOne("Matchketing.Embudo.Dominio.Etapa", null)
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Matchketing.Embudo.Dominio.Embudo", b =>
                {
                    b.Navigation("Etapas");
                });
#pragma warning restore 612, 618
        }
    }
}
