// <auto-generated />
using System;
using AlxorCore.Integraciones.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Integraciones.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(IntegracionesDbContext))]
    partial class IntegracionesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("integraciones")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Integraciones.Dominio.ClaveApi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("HashSecreto")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_secreto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("prefijo");

                    b.Property<DateTimeOffset?>("RevocadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocada_en");

                    b.Property<DateTimeOffset?>("UltimoUsoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_uso_en");

                    b.HasKey("Id");

                    b.HasIndex("HashSecreto")
                        .IsUnique()
                        .HasDatabaseName("ux_clave_api_hash");

                    b.ToTable("clave_api", "integraciones");
                });

            modelBuilder.Entity("AlxorCore.Integraciones.Dominio.EntregaWebhook", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset?>("EntregadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entregada_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("evento");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ProximoIntento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proximo_intento");

                    b.Property<string>("SecretoFirma")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("secreto_firma");

                    b.Property<Guid>("SuscripcionId")
                        .HasColumnType("uuid")
                        .HasColumnName("suscripcion_id");

                    b.Property<string>("UltimaRespuesta")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("ultima_respuesta");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Estado", "ProximoIntento")
                        .HasDatabaseName("ix_entrega_webhook_estado");

                    b.ToTable("entrega_webhook", "integraciones");
                });

            modelBuilder.Entity("AlxorCore.Integraciones.Dominio.SuscripcionWebhook", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Eventos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("eventos");

                    b.Property<string>("Secreto")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("secreto");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Activa")
                        .HasDatabaseName("ix_suscripcion_webhook_empresa");

                    b.ToTable("suscripcion_webhook", "integraciones");
                });
#pragma warning restore 612, 618
        }
    }
}
