<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AlxorCore.Gastos</RootNamespace>
    <AssemblyName>AlxorCore.Gastos</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlxorCore.Nucleo\AlxorCore.Nucleo.csproj" />
    <ProjectReference Include="..\AlxorCore.Terceros\AlxorCore.Terceros.csproj" />
    <ProjectReference Include="..\AlxorCore.Organizacion\AlxorCore.Organizacion.csproj" />
  </ItemGroup>

</Project>
