<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>AlxorCore.Migracion</RootNamespace><AssemblyName>AlxorCore.Migracion</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AlxorCore.Nucleo\AlxorCore.Nucleo.csproj" />
    <ProjectReference Include="..\AlxorCore.Terceros\AlxorCore.Terceros.csproj" />
    <ProjectReference Include="..\AlxorCore.Catalogo\AlxorCore.Catalogo.csproj" />
    <ProjectReference Include="..\AlxorCore.Contabilidad\AlxorCore.Contabilidad.csproj" />
    <ProjectReference Include="..\AlxorCore.Tesoreria\AlxorCore.Tesoreria.csproj" />
    <ProjectReference Include="..\AlxorCore.Agro\AlxorCore.Agro.csproj" />
  </ItemGroup>
</Project>
