// <auto-generated />
using System;
using AlxorCore.Compras.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Compras.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ComprasDbContext))]
    [Migration("20260822114331_SerieEnDocumentosCompra")]
    partial class SerieEnDocumentosCompra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("compras")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Compras.Dominio.AlbaranCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<string>("Referencia")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("referencia");

                    b.Property<string>("Serie")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("serie");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "PedidoId")
                        .HasDatabaseName("ix_albaran_empresa_pedido");

                    b.ToTable("albaran_compra", "compras");
                });

            modelBuilder.Entity("AlxorCore.Compras.Dominio.PedidoCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<Guid?>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("ProveedorTexto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("proveedor_texto");

                    b.Property<string>("Serie")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("serie");

                    b.Property<Guid?>("SolicitudOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitud_origen_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Estado")
                        .HasDatabaseName("ix_pedido_empresa_estado");

                    b.HasIndex("EmpresaId", "Ejercicio", "ProveedorId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_pedido_serie_proveedor");

                    b.ToTable("pedido_compra", "compras");
                });

            modelBuilder.Entity("AlxorCore.Compras.Dominio.SolicitudCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas");

                    b.Property<string>("ProveedorSugerido")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("proveedor_sugerido");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Estado")
                        .HasDatabaseName("ix_solicitud_empresa_estado");

                    b.ToTable("solicitud_compra", "compras");
                });

            modelBuilder.Entity("AlxorCore.Compras.Dominio.AlbaranCompra", b =>
                {
                    b.OwnsMany("AlxorCore.Compras.Dominio.LineaAlbaran", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("descripcion");

                            b1.Property<Guid>("LineaPedidoId")
                                .HasColumnType("uuid")
                                .HasColumnName("linea_pedido_id");

                            b1.Property<Guid?>("ProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("producto_id");

                            b1.Property<Guid>("albaran_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("albaran_id");

                            b1.ToTable("linea_albaran", "compras");

                            b1.WithOwner()
                                .HasForeignKey("albaran_id");
                        });

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("AlxorCore.Compras.Dominio.PedidoCompra", b =>
                {
                    b.OwnsMany("AlxorCore.Compras.Dominio.LineaPedido", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad");

                            b1.Property<decimal>("CantidadFacturada")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad_facturada");

                            b1.Property<decimal>("CantidadRecibida")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad_recibida");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("descripcion");

                            b1.Property<decimal>("PrecioUnitario")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("precio_unitario");

                            b1.Property<Guid?>("ProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("producto_id");

                            b1.Property<Guid>("pedido_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("pedido_id");

                            b1.ToTable("linea_pedido", "compras");

                            b1.WithOwner()
                                .HasForeignKey("pedido_id");
                        });

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("AlxorCore.Compras.Dominio.SolicitudCompra", b =>
                {
                    b.OwnsMany("AlxorCore.Compras.Dominio.LineaSolicitud", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("descripcion");

                            b1.Property<Guid>("solicitud_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("solicitud_id");

                            b1.ToTable("linea_solicitud", "compras");

                            b1.WithOwner()
                                .HasForeignKey("solicitud_id");
                        });

                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
