// <auto-generated />
using System;
using AlxorCore.Recepcion.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Recepcion.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(RecepcionDbContext))]
    [Migration("20260821125449_MigracionInicialRecepcion")]
    partial class MigracionInicialRecepcion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("recepcion")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Recepcion.Dominio.FacturaRecibida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AsuntoCorreo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("asunto_correo");

                    b.Property<decimal?>("BaseImponible")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_imponible");

                    b.Property<string>("CodigoIva")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_iva");

                    b.Property<byte[]>("Contenido")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("contenido");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaFactura")
                        .HasColumnType("date")
                        .HasColumnName("fecha_factura");

                    b.Property<DateTimeOffset>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_recepcion");

                    b.Property<Guid?>("GastoId")
                        .HasColumnType("uuid")
                        .HasColumnName("gasto_id");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_rechazo");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("numero_factura");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origen");

                    b.Property<decimal?>("PorcentajeIrpf")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_irpf");

                    b.Property<Guid?>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("ProveedorTexto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("proveedor_texto");

                    b.Property<string>("RemitenteCorreo")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("remitente_correo");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tipo_contenido");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Estado")
                        .HasDatabaseName("ix_factura_recibida_empresa_estado");

                    b.ToTable("factura_recibida", "recepcion");
                });
#pragma warning restore 612, 618
        }
    }
}
