// <auto-generated />
using System;
using AlxorCore.Produccion.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Produccion.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ProduccionDbContext))]
    partial class ProduccionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("produccion")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Produccion.Dominio.OrdenFabricacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("cantidad");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("producto_nombre");

                    b.Property<DateTimeOffset?>("TerminadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminada_en");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Ejercicio", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_orden_serie");

                    b.ToTable("orden_fabricacion", "produccion");
                });

            modelBuilder.Entity("AlxorCore.Produccion.Dominio.OrdenFabricacion", b =>
                {
                    b.OwnsMany("AlxorCore.Produccion.Dominio.ComponentePlan", "Componentes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("CantidadTotal")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad_total");

                            b1.Property<decimal>("CantidadUnitaria")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad_unitaria");

                            b1.Property<Guid>("ComponenteId")
                                .HasColumnType("uuid")
                                .HasColumnName("componente_id");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("nombre");

                            b1.Property<Guid>("orden_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("orden_id");

                            b1.ToTable("componente_plan", "produccion");

                            b1.WithOwner()
                                .HasForeignKey("orden_id");
                        });

                    b.Navigation("Componentes");
                });
#pragma warning restore 612, 618
        }
    }
}
