// <auto-generated />
using System;
using AlxorCore.Catalogo.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Catalogo.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(CatalogoDbContext))]
    [Migration("20260928152319_ConceptosJerarquiaAcreedor")]
    partial class ConceptosJerarquiaAcreedor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalogo")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Catalogo.Dominio.ConceptoLinea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcreedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("acreedor_id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ambito");

                    b.Property<string>("BasePorcentaje")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Linea")
                        .HasColumnName("base_porcentaje");

                    b.Property<string>("Calculo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("calculo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CuentaContable")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cuenta_contable");

                    b.Property<string>("Efecto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("efecto");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("Reparto")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("reparto");

                    b.Property<string>("Sentido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sentido");

                    b.Property<string>("TextoDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("texto_documento");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_concepto_linea_grupo_codigo");

                    b.ToTable("concepto_linea", "catalogo");
                });

            modelBuilder.Entity("AlxorCore.Catalogo.Dominio.ExistenciaSimple", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ProductoId")
                        .IsUnique()
                        .HasDatabaseName("ux_existencia_simple_empresa_producto");

                    b.ToTable("existencia_simple", "catalogo");
                });

            modelBuilder.Entity("AlxorCore.Catalogo.Dominio.Familia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<Guid?>("PadreId")
                        .HasColumnType("uuid")
                        .HasColumnName("padre_id");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId", "PadreId")
                        .HasDatabaseName("ix_familia_grupo_padre");

                    b.ToTable("familia", "catalogo");
                });

            modelBuilder.Entity("AlxorCore.Catalogo.Dominio.HistoricoPrecio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_compra");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_venta");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registrado_en");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId", "ProductoId", "RegistradoEn")
                        .HasDatabaseName("ix_historico_precio_producto");

                    b.ToTable("historico_precio", "catalogo");
                });

            modelBuilder.Entity("AlxorCore.Catalogo.Dominio.MovimientoStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("cantidad");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("StockResultante")
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("stock_resultante");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ProductoId", "CreadoEn")
                        .HasDatabaseName("ix_movimiento_stock_producto");

                    b.ToTable("movimiento_stock", "catalogo");
                });

            modelBuilder.Entity("AlxorCore.Catalogo.Dominio.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActividadNegocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("actividad_negocio_id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<decimal>("AjustePrecioComponentes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(7,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ajuste_precio_componentes");

                    b.Property<string>("CodigoArancelario")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_arancelario");

                    b.Property<string>("CodigoIva")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_iva");

                    b.Property<string>("Composicion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Fabricacion")
                        .HasColumnName("tipo_composicion");

                    b.Property<bool>("ControlarStock")
                        .HasColumnType("boolean")
                        .HasColumnName("controlar_stock");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<bool>("EsCompuesto")
                        .HasColumnType("boolean")
                        .HasColumnName("es_compuesto");

                    b.Property<bool>("EsPlantilla")
                        .HasColumnType("boolean")
                        .HasColumnName("es_plantilla");

                    b.Property<decimal>("FactorCompra")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("factor_compra");

                    b.Property<decimal>("FactorVenta")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("factor_venta");

                    b.Property<string>("Familia")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("familia");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("uuid")
                        .HasColumnName("familia_id");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("PaisOrigen")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("pais_origen");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("peso_kg");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_compra");

                    b.Property<bool>("PrecioSegunComponentes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("precio_segun_componentes");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<Guid?>("ProductoPadreId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_padre_id");

                    b.Property<Guid?>("ProveedorHabitualId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_habitual_id");

                    b.Property<string>("Referencia")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("referencia");

                    b.Property<string>("Seguimiento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("seguimiento");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad");

                    b.Property<string>("UnidadCompra")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad_compra");

                    b.Property<string>("UnidadVenta")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad_venta");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId")
                        .HasDatabaseName("ix_producto_familia");

                    b.HasIndex("GrupoId", "Nombre")
                        .HasDatabaseName("ix_producto_grupo_nombre");

                    b.ToTable("producto", "catalogo");
                });

            modelBuilder.Entity("AlxorCore.Catalogo.Dominio.Tarifa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_tarifa_grupo_codigo");

                    b.ToTable("tarifa", "catalogo");
                });

            modelBuilder.Entity("AlxorCore.Catalogo.Dominio.TipoIva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("clase");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Impuesto")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Iva")
                        .HasColumnName("impuesto");

                    b.Property<string>("MencionFactura")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("mencion_factura");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje");

                    b.Property<decimal>("RecargoEquivalencia")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("recargo_equivalencia");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_tipo_iva_empresa_codigo");

                    b.ToTable("tipo_iva", "catalogo");
                });

            modelBuilder.Entity("AlxorCore.Catalogo.Dominio.ConceptoLinea", b =>
                {
                    b.OwnsMany("AlxorCore.Catalogo.Dominio.AsignacionConcepto", "Asignaciones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("AcreedorId")
                                .HasColumnType("uuid")
                                .HasColumnName("acreedor_id");

                            b1.Property<DateOnly?>("Desde")
                                .HasColumnType("date")
                                .HasColumnName("desde");

                            b1.Property<Guid?>("FamiliaId")
                                .HasColumnType("uuid")
                                .HasColumnName("familia_id");

                            b1.Property<DateOnly?>("Hasta")
                                .HasColumnType("date")
                                .HasColumnName("hasta");

                            b1.Property<Guid?>("ProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("producto_id");

                            b1.Property<Guid?>("TerceroId")
                                .HasColumnType("uuid")
                                .HasColumnName("tercero_id");

                            b1.Property<string>("TipoTercero")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("tipo_tercero");

                            b1.Property<decimal?>("Valor")
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("valor");

                            b1.Property<Guid>("concepto_linea_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("concepto_linea_id")
                                .HasDatabaseName("ix_asignacion_concepto_concepto");

                            b1.ToTable("asignacion_concepto", "catalogo");

                            b1.WithOwner()
                                .HasForeignKey("concepto_linea_id");
                        });

                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("AlxorCore.Catalogo.Dominio.Producto", b =>
                {
                    b.OwnsMany("AlxorCore.Catalogo.Dominio.AtributoVariante", "Atributos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("nombre");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("valor");

                            b1.Property<Guid>("producto_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("producto_id");

                            b1.ToTable("atributo_variante", "catalogo");

                            b1.WithOwner()
                                .HasForeignKey("producto_id");
                        });

                    b.OwnsMany("AlxorCore.Catalogo.Dominio.ComponenteArticulo", "Componentes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad");

                            b1.Property<Guid>("ComponenteId")
                                .HasColumnType("uuid")
                                .HasColumnName("componente_id");

                            b1.Property<Guid>("producto_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("producto_id");

                            b1.ToTable("componente_articulo", "catalogo");

                            b1.WithOwner()
                                .HasForeignKey("producto_id");
                        });

                    b.Navigation("Atributos");

                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("AlxorCore.Catalogo.Dominio.Tarifa", b =>
                {
                    b.OwnsMany("AlxorCore.Catalogo.Dominio.LineaTarifa", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("CantidadMinima")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad_minima");

                            b1.Property<DateOnly?>("Desde")
                                .HasColumnType("date")
                                .HasColumnName("desde");

                            b1.Property<Guid?>("FamiliaId")
                                .HasColumnType("uuid")
                                .HasColumnName("familia_id");

                            b1.Property<DateOnly?>("Hasta")
                                .HasColumnType("date")
                                .HasColumnName("hasta");

                            b1.Property<decimal>("PorcentajeDescuento")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("porcentaje_descuento");

                            b1.Property<decimal?>("Precio")
                                .HasColumnType("numeric(15,6)")
                                .HasColumnName("precio");

                            b1.Property<Guid?>("ProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("producto_id");

                            b1.Property<Guid>("tarifa_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("tarifa_id")
                                .HasDatabaseName("ix_linea_tarifa_tarifa");

                            b1.ToTable("linea_tarifa", "catalogo");

                            b1.WithOwner()
                                .HasForeignKey("tarifa_id");
                        });

                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
